//! tamescroll — a narrow shell that opens only the feeds, cleaned.
//!
//! The blocking engine is Brave's `adblock` crate. We do not implement
//! filtering ourselves; we hand it EasyList-syntax rules and ask it what
//! to hide for a given URL. See NOTICE.

use std::collections::HashMap;
use std::sync::{Arc, Mutex, RwLock};

use adblock::cosmetic_filter_cache::ProceduralOrActionFilter;
use adblock::Engine;
use serde::Serialize;
use tauri::{Manager, WebviewUrl, WebviewWindowBuilder};

mod appupdate;
mod ota;
mod rules;

/// Stage A gaze blur (docs/plan.md Phase 4): plain CSS, opt-in, appended to
/// the injected stylesheet only when the launcher's blur toggle is on. Not
/// EasyList syntax and not run through the cosmetic-filter engine — these
/// files are `filter: blur(...)` rules on chosen media selectors, kept
/// separate from rules/*.txt because blurring is a personal choice and the
/// mechanism (plain CSS) differs from cosmetic hiding.
const BLUR_PLATFORMS: &[&str] = &["youtube", "reddit", "x", "tiktok"];

fn blur_css(platform_id: &str) -> String {
    if !BLUR_PLATFORMS.contains(&platform_id) {
        return String::new();
    }
    ota::rules_text(&format!("blur/{platform_id}.css"))
}

/// Stage B gaze bundle (docs/gaze-research.md): the built JS runtime that
/// base64-embeds BlazeFace and blurs-first via injected CSS, then
/// unblurs faceless media via on-device inference. Generated by
/// `npm run build:gaze` in app/gaze/ — a committed generated artifact,
/// same treatment as the vendored rule-list snapshots in rules/vendor/.
const GAZE_INIT_JS: &str = include_str!("../gaze-init.js");

/// Normalises the launcher's gaze mode: unknown values fall back to
/// "off" rather than risk an unrecognised mode silently doing nothing
/// while claiming to be active.
fn gaze_mode(mode: &str) -> &'static str {
    match mode {
        "smart" => "smart",
        "blur" => "blur",
        _ => "off",
    }
}

/// The gaze mode the launcher last told us about. Desktop windows bake
/// the mode into their creation-time script; Android navigates one
/// long-lived webview, so page loads must read the CURRENT mode from
/// somewhere Rust-side — this. Updated by `open_platform` and the
/// `set_gaze_mode` command.
static GAZE_STATE: Mutex<&'static str> = Mutex::new("off");

fn set_gaze_state(mode: &str) {
    *GAZE_STATE.lock().unwrap() = gaze_mode(mode);
}

fn gaze_state() -> &'static str {
    *GAZE_STATE.lock().unwrap()
}

/// Blur radius presets the launcher can pick (px). Anything else
/// normalises to the medium default so a bad invoke can never produce a
/// 0px "blur" that reports itself active while doing nothing.
fn blur_strength_px(px: u32) -> u32 {
    match px {
        8 | 16 | 28 => px,
        _ => 16,
    }
}

/// Launcher-chosen blur strength, same lifecycle as GAZE_STATE: desktop
/// windows bake it into their creation-time script, Android's single
/// webview re-reads it on every page load. Updated by `open_platform`
/// and the `set_blur_strength` command.
static BLUR_PX: Mutex<u32> = Mutex::new(16);

fn set_blur_px(px: u32) {
    *BLUR_PX.lock().unwrap() = blur_strength_px(px);
}

fn blur_px() -> u32 {
    *BLUR_PX.lock().unwrap()
}

/// Declared user gender for the protection engine's gender stage
/// (docs/handoff-protection-engine.md decision #3). Same lifecycle as
/// GAZE_STATE: launcher-set, desktop windows read it per page load,
/// Android's single webview re-reads on navigation. "unset" = no
/// declaration; the bundle then covers any face (fail-safe).
static GENDER_STATE: Mutex<&'static str> = Mutex::new("unset");

fn user_gender_norm(g: &str) -> &'static str {
    match g {
        "man" => "man",
        "woman" => "woman",
        _ => "unset",
    }
}

fn set_user_gender_state(g: &str) {
    *GENDER_STATE.lock().unwrap() = user_gender_norm(g);
}

fn user_gender() -> &'static str {
    *GENDER_STATE.lock().unwrap()
}

/// User-added filter terms (Settings -> Filters). Seed list ships inside
/// the gaze bundle; these ride the smart boot script as a JSON array so
/// the matcher can extend itself. Same launcher-set lifecycle as the
/// rest of the gaze state.
static USER_TERMS: Mutex<Vec<String>> = Mutex::new(Vec::new());

/// The launcher's bring-back prefs, Rust-held for the same reason as
/// GAZE_STATE: Android's single webview injects per page load, so page
/// loads must read the CURRENT prefs, not ones baked at window creation.
static SHOWN_STATE: Mutex<Vec<String>> = Mutex::new(Vec::new());

fn set_shown_state(shown: Vec<String>) {
    *SHOWN_STATE.lock().unwrap() = shown;
}

#[cfg_attr(not(target_os = "android"), allow(dead_code))] // android page loads
fn shown_state() -> Vec<String> {
    SHOWN_STATE.lock().unwrap().clone()
}

fn set_user_terms_state(terms: Vec<String>) {
    let mut cleaned: Vec<String> = terms
        .into_iter()
        .map(|t| t.trim().to_string())
        .filter(|t| !t.is_empty() && t.len() <= 100)
        .collect();
    cleaned.truncate(200);
    *USER_TERMS.lock().unwrap() = cleaned;
}

fn user_terms_json() -> String {
    serde_json::to_string(&*USER_TERMS.lock().unwrap()).unwrap_or_else(|_| "[]".into())
}

/// The CSS variables every blur consumer resolves against: Stage A
/// sheets use `var(--ts-blur, 16px)`, Stage B's class styles use
/// `var(--ts-blur-strong, 24px)` — positively detected content earns
/// the heavier blur. Ships ahead of the blur CSS, so the fallbacks only
/// apply if this rule is missing entirely (e.g. an old injected sheet).
fn blur_vars_css(px: u32) -> String {
    let px = blur_strength_px(px);
    format!(
        ":root {{ --ts-blur: {px}px; --ts-blur-strong: {strong}px; }}\n",
        strong = px * 3 / 2
    )
}

/// Which platform a live page host belongs to, if any. Hosts arrive
/// with mobile/www prefixes (m.youtube.com after the UA redirect —
/// the lesson behind dropping per-window host filters), so match on
/// the platform's root domain.
#[cfg_attr(not(target_os = "android"), allow(dead_code))]
fn platform_for_host(host: &str) -> Option<&'static Platform> {
    // Same suffix semantics as universal_injection_script's JS matcher
    // (root or ".root" suffix) — the two matchers diverging meant
    // old.reddit.com got hide-CSS but no blur (review 2026-08-19).
    // Ports stripped for the same reason.
    let h = host.split(':').next().unwrap_or(host);
    PLATFORMS.iter().find(|p| {
        let root = platform_root(p.url);
        h == root || h.ends_with(&format!(".{root}"))
    })
}

/// The script a page load must evaluate to honour the current gaze
/// mode: blur CSS for "blur" and "smart", plus the Stage B runtime for
/// "smart". None when the mode is off, the host is not a platform, or
/// the platform has no blur sheet yet (Instagram). Idempotent — the
/// style-id guard lets callers eval it at both Started and Finished
/// page events so blur lands as early as the document exists.
///
/// Smart mode deliberately ships NO Stage A sheet: those selectors have
/// no class hook, so Stage B's class-removal unblur could never win
/// against them — the whole mode would collapse into blur-all (review
/// finding, 2026-08-19). Desktop draws the same line in open_platform
/// (`page_css(.., mode == "blur", ..)`); Stage B blurs-first itself.
/// The full rules payload for one page load: engine cosmetics +
/// scriptlets + our surfaces at the CURRENT shown prefs. Android's only
/// full-rules delivery (the universal plugin script carries surfaces
/// only — owner-reported 2026-08-20 as "ad blocking does not work at
/// all" on the phone). Guarded so Started + Finished double-eval is a
/// no-op: scriptlets are not all idempotent.
#[cfg_attr(not(target_os = "android"), allow(dead_code))] // android page loads
fn page_load_rules_script(url: &str) -> Option<String> {
    let platform = platform_for_host(platform_root(url))?;
    let resources = engine().url_cosmetic_resources(url);
    let script = injection_script(
        // Blur is deliberately NOT part of this payload: the gaze
        // page-load script owns the Stage A sheet and the Stage B boot.
        &page_css(url, platform.id, false, &shown_state()),
        &resources.injected_script,
    );
    Some(format!(
        r#"
(function () {{
  if (window.__TS_RULES__) return;
  window.__TS_RULES__ = 1;
  // The universal plugin script already planted a surfaces-only sheet
  // under the SAME id at document start (its job: instant hiding before
  // first paint). Drop it so the full payload's apply() isn't a no-op —
  // emulator evidence 2026-08-20: cssLen stayed 2332 (surfaces-only)
  // with the guard set, ads CSS never landed.
  try {{
    var ts_u = document.getElementById("tamescroll-rules");
    if (ts_u && ts_u.parentNode) ts_u.parentNode.removeChild(ts_u);
  }} catch (e) {{}}
{script}
}})();
"#
    ))
}

fn page_load_gaze_script(url: &str, mode: &str) -> Option<String> {
    let mode = gaze_mode(mode);
    let platform = platform_for_host(platform_root(url))?;
    if blur_css(platform.id).is_empty() {
        return None;
    }
    // The compulsory NSFW-removal tier (handoff decision #1) means the
    // Stage B bundle boots in EVERY mode — pipeline-plan.mjs inside the
    // bundle decides what actually runs. Only blur-all adds the Stage A
    // sheet on top.
    if mode != "blur" {
        return Some(gaze_script(mode));
    }
    let css_json =
        serde_json::to_string(&format!("{}{}", blur_vars_css(blur_px()), blur_css(platform.id)))
            .ok()?;
    Some(format!(
        r#"
(function () {{
  try {{
    if (document.getElementById("ts-gaze-blur")) return;
    var s = document.createElement("style");
    s.id = "ts-gaze-blur";
    s.textContent = {css_json};
    (document.head || document.documentElement).appendChild(s);
  }} catch (e) {{}}
}})();
{boot}"#,
        boot = gaze_script("blur")
    ))
}

// NOTE (review 2026-08-23 #1): a string-literal + page-side eval()
// fallback for the Finished event was tried here to halve the 7.5MB
// parse cost — and reverted. webview.eval bypasses page CSP for the
// injected string itself, but eval() INSIDE it runs under the page's
// code-generation policy: Reddit/X ship CSPs without unsafe-eval and
// YouTube enforces trusted-types, so the fallback silently did nothing
// on exactly the race it existed to cover. Until a Rust-side signal
// exists for "Started raced", both events eval the full bundle; the
// __TS_GAZE_BUNDLE__ guard keeps execution single-shot.

/// Script that boots gaze Stage B in every normalised mode (compulsory
/// NSFW-removal tier — the in-page plan gates what actually runs).
/// Wrapped in its own try/catch on top of the bundle's internal
/// fail-open handling — a syntax-level break in the generated bundle
/// must not be able to take the rest of the injected script down with
/// it, matching the pattern already used for scriptlets below.
fn gaze_script(mode: &str) -> String {
    let mode = gaze_mode(mode);
    // Stage B's class styles blur through var(--ts-blur-strong); the
    // launcher's strength choice has to reach the page inline because
    // smart mode ships no stylesheet of its own to carry a :root rule.
    let px = blur_px();
    let strong = px * 3 / 2;
    let gender = user_gender();
    let terms = user_terms_json();
    format!(
        r#"
(function () {{
  try {{
    if (window.__TS_GAZE_BUNDLE__) return;
    window.__TS_GAZE_MODE = "{mode}";
    window.__TS_GAZE_GENDER = "{gender}";
    window.__TS_USER_TERMS = {terms};
    var tsRoot = document.documentElement;
    if (tsRoot) {{
      tsRoot.style.setProperty("--ts-blur", "{px}px");
      tsRoot.style.setProperty("--ts-blur-strong", "{strong}px");
    }}
{GAZE_INIT_JS}
  }} catch (e) {{}}
}})();
"#
    )
}

/// Our own surfaces' CSS (docs/plan.md Phase 3 settings pane): one rule
/// per selector, same hard-won-lesson formatting as `cosmetic_css` below,
/// for every surface not in `shown` — always_on surfaces (ads) are never
/// skipped, no matter what `shown` contains, because ad-hiding is not
/// user-toggleable (VISION.md). `shown` entries that don't name a real
/// surface for this platform are simply never matched, i.e. ignored.
///
/// Every rule of the platform ships regardless of its `domain` column:
/// the injected CSS is built ONCE per window, but Android's UA redirect
/// moves that same window from www.youtube.com to m.youtube.com (seen on
/// the emulator 2026-08-18 — the Shorts tab survived precisely because
/// the m.youtube rules were host-filtered out at injection time).
/// Desktop and mobile selectors target disjoint element sets (ytd-* vs
/// ytm-*), so cross-shipping is harmless where filtering was actively
/// wrong.
fn surfaces_css(platform_id: &str, shown: &[String]) -> String {
    let Some(surfaces) = rules::platform_surfaces(platform_id) else {
        return String::new();
    };

    let mut css = String::new();
    for surface in surfaces {
        let is_shown = !surface.always_on && shown.iter().any(|id| id == surface.id);
        if is_shown {
            continue;
        }
        // The `domain##` column is NOT enforced here — every selector in
        // a platform's file ships to every host the universal script
        // matches for that platform (m./www./subdomains). That is
        // deliberate for ytm-*/ytd-* (disjoint namespaces, and the UA
        // redirect happens after injection), but it means a
        // non-namespaced selector under `m.youtube.com##` ALSO applies
        // on www/music/studio. Write selectors accordingly; do not
        // trust the domain column to scope them (review 2026-08-19).
        for (_domain, selector) in &surface.rules {
            css.push_str(selector);
            css.push_str(" { display: none !important; }\n");
        }
    }
    css
}

/// The full stylesheet injected into a platform window: cosmetic hiding
/// always, our own surfaces next (minus whatever the user chose to show),
/// Stage A blur appended last (same stylesheet, no separate style
/// element) only when the launcher toggle is on.
/// Android's WebView paints a translucent teal rectangle behind every
/// tapped element. Owner, 2026-08-26, with a phone screenshot of
/// m.youtube's search button wearing one: "on selection it shows the
/// blue thing at many places making it feel unpolished".
///
/// The launcher has killed this since the #10 polish pass
/// (app/src/styles.css) — platform pages never did, because our injected
/// CSS only ever carried rules and blur. It is purely visual feedback the
/// sites already replace with their own ripples, so removing it takes
/// nothing away, and it is desktop-inert (the property does nothing in
/// WebView2).
fn chrome_css() -> &'static str {
    "* { -webkit-tap-highlight-color: transparent !important; }
"
}

fn page_css(url: &str, platform_id: &str, blur: bool, shown: &[String]) -> String {
    let mut css = cosmetic_css(url);
    css.push_str(chrome_css());
    css.push_str(&surfaces_css(platform_id, shown));
    if blur {
        css.push_str(&blur_vars_css(blur_px()));
        css.push_str(&blur_css(platform_id));
    }
    css
}

/// The engine, swappable at runtime: a rules OTA refresh (ota.rs) builds
/// a replacement from the updated lists and drops it in — the engine
/// stays put architecturally, only the data moves. Arc because a page
/// injection may be reading the old engine while a refresh installs the
/// new one. Building from the full vendored set takes on the order of a
/// second, so `run()` warms it on a background thread instead of paying
/// that cost on the first tile click.
static ENGINE: RwLock<Option<Arc<Engine>>> = RwLock::new(None);

fn engine() -> Arc<Engine> {
    if let Some(e) = ENGINE.read().unwrap().as_ref() {
        return e.clone();
    }
    let built = Arc::new(rules::build_engine());
    let mut w = ENGINE.write().unwrap();
    // A racing warm-up thread may have won; keep whichever landed first.
    w.get_or_insert(built).clone()
}

/// Should this outbound request be blocked?
///
/// THE GAP THIS CLOSES (found 2026-08-25, owner: "ads started appearing
/// again... why were they able to get through?"): the adblock engine has
/// been in this app since Phase 2.5 with EasyList, EasyPrivacy and the
/// uBO lists compiled in — and it was only ever asked
/// `url_cosmetic_resources`. Cosmetic filtering hides ELEMENTS. It
/// cannot stop a request, and a YouTube pre-roll is not an element: it
/// is video served through the player itself. Measured on the dev app,
/// a single watch page let all of these reach the network:
///   googleads.g.doubleclick.net/pagead/id
///   static.doubleclick.net/instream/ad_status.js
///   www.youtube.com/ptracking
///   .../pagead/viewthroughconversion/...
/// So this was never a regression. Network blocking was never wired at
/// all; what changed is which ads YouTube chose to serve.
///
/// `source_url` is the page making the request (first-party context) and
/// `resource_type` is the fetch destination ("script", "image", "xhr",
/// ""), both of which the filter lists genuinely use — a rule can be
/// third-party-only, or script-only, so passing them through is the
/// difference between blocking ads and breaking the site.
/// Resources we answer ourselves, on whatever origin asked for them.
///
/// YouTube sends `require-trusted-types-for 'script'`, which is why
/// every earlier attempt at moving inference into a Worker failed: a
/// blob: url cannot be loaded as a TrustedScriptURL there. A SAME-ORIGIN
/// url can (measured 2026-08-27: one of YouTube's own scripts runs
/// inside a Worker on its own page). Nothing serves such a url but us.
///
/// The path is deliberately unmistakable and is never a real platform
/// url; returning None is the normal case and leaves the request
/// exactly as it was.
pub(crate) fn synthetic_resource(url: &str) -> Option<&'static str> {
    let path = url.split('?').next().unwrap_or(url);
    // The SAME artifact the page gets. It boots the worker half when it
    // finds no `document`, so a second bundle would only be a second copy
    // of tfjs and of all four models -- 17MB of APK for identical bytes.
    if path.ends_with("/__tamescroll/gaze-init.js") {
        return Some(GAZE_INIT_JS);
    }
    None
}

pub(crate) fn blocks_request(url: &str, source_url: &str, resource_type: &str) -> bool {
    // Never gamble on our own IPC or the launcher: a false positive here
    // bricks the app, and neither can serve an ad.
    if url.starts_with("tauri://") || url.starts_with("ipc://") || url.contains("tauri.localhost") {
        return false;
    }
    // An unparseable URL is not something we can reason about, and this
    // runs inside every page load: degrade to "allow" rather than panic.
    let Ok(req) = adblock::request::Request::new(url, source_url, resource_type, "GET") else {
        return false;
    };
    // should_block() rather than `filter.is_some()`: a blocking rule can
    // be cancelled by an exception rule, and the unbreak lists exist
    // precisely to cancel over-broad blocks. Reading the raw match would
    // ignore every one of them and break the sites we are cleaning.
    engine().check_network_request(&req).should_block()
}

/// Bridge for the Android WebViewClient (`shouldInterceptRequest`) and
/// any other host-side interceptor. Kept deliberately thin: the decision
/// lives in one place so desktop and Android can never drift.
#[tauri::command]
fn should_block_request(url: String, source_url: String, resource_type: String) -> bool {
    blocks_request(&url, &source_url, &resource_type)
}

/// Installs the network block hook on a desktop WebView2.
///
/// The desktop counterpart of Android's `shouldInterceptRequest`. Tauri
/// and wry expose no general http interception, so this reaches the
/// underlying ICoreWebView2 through `with_webview` and subscribes to
/// WebResourceRequested with an ALL filter.
///
/// A blocked request is answered with an empty 204 rather than an
/// error, for the same reason as on Android: a hard failure makes pages
/// retry and sometimes render their own "content blocked" placeholder,
/// where an empty success is silent.
///
/// Every failure path leaves the webview untouched — a webview with no
/// hook shows ads, a webview with a broken hook shows nothing at all.
#[cfg(target_os = "windows")]
fn install_request_blocker(window: &tauri::WebviewWindow) {
    use webview2_com::Microsoft::Web::WebView2::Win32::{
        COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL, ICoreWebView2, ICoreWebView2Environment,
        ICoreWebView2WebResourceRequestedEventArgs,
    };
    use webview2_com::WebResourceRequestedEventHandler;
    use windows::core::{Interface, PCWSTR};

    let _ = window.with_webview(|webview| unsafe {
        let core: ICoreWebView2 = match webview.controller().CoreWebView2() {
            Ok(c) => c,
            Err(_) => return,
        };
        let wide: Vec<u16> = "* ".encode_utf16().collect();
        if core
            .AddWebResourceRequestedFilter(
                PCWSTR(wide.as_ptr()),
                COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL,
            )
            .is_err()
        {
            return;
        }
        let env: ICoreWebView2Environment = match core
            .cast::<webview2_com::Microsoft::Web::WebView2::Win32::ICoreWebView2_2>()
            .and_then(|w| w.Environment())
        {
            Ok(e) => e,
            Err(_) => return,
        };
        let mut token = Default::default();
        let _ = core.add_WebResourceRequested(
            &WebResourceRequestedEventHandler::create(Box::new(
                move |sender: Option<ICoreWebView2>,
                      args: Option<ICoreWebView2WebResourceRequestedEventArgs>| {
                    let (Some(sender), Some(args)) = (sender, args) else {
                        return Ok(());
                    };
                    let Ok(request) = args.Request() else { return Ok(()) };
                    // These COM getters write into an out-param and hand
                    // us ownership of the buffer; PWSTR::to_string reads
                    // it, and CoTaskMemFree releases it. Skipping the
                    // free leaks on every single request the page makes.
                    let mut raw = windows::core::PWSTR::null();
                    if request.Uri(&mut raw).is_err() {
                        return Ok(());
                    }
                    let url = raw.to_string().unwrap_or_default();
                    windows::Win32::System::Com::CoTaskMemFree(Some(raw.0 as *const _));
                    if !url.starts_with("http") {
                        return Ok(());
                    }
                    // The page making the request. Without it every rule
                    // reads as first-party and the third-party options
                    // that carry most ad rules never fire.
                    let mut raw_src = windows::core::PWSTR::null();
                    let source = if sender.Source(&mut raw_src).is_ok() {
                        let v = raw_src.to_string().unwrap_or_default();
                        windows::Win32::System::Com::CoTaskMemFree(Some(raw_src.0 as *const _));
                        v
                    } else {
                        String::new()
                    };
                    // Our own script, on the page's own origin — see
                    // synthetic_resource for why that is the only shape
                    // of Worker YouTube's Trusted Types will load.
                    if let Some(body) = synthetic_resource(&url) {
                        if let Some(stream) =
                            windows::Win32::UI::Shell::SHCreateMemStream(Some(body.as_bytes()))
                        {
                            if let Ok(response) = env.CreateWebResourceResponse(
                                Some(&stream),
                                200,
                                windows::core::w!("OK"),
                                windows::core::w!(
                                    "Content-Type: text/javascript\r\nCache-Control: no-store"
                                ),
                            ) {
                                let _ = args.SetResponse(&response);
                            }
                        }
                        return Ok(());
                    }
                    if !blocks_request(&url, &source, "other") {
                        return Ok(());
                    }
                    if let Ok(response) = env.CreateWebResourceResponse(
                        None::<&windows::Win32::System::Com::IStream>,
                        204,
                        windows::core::w!("No Content"),
                        windows::core::w!(""),
                    ) {
                        let _ = args.SetResponse(&response);
                    }
                    Ok(())
                },
            )),
            &mut token,
        );
    });
}

#[cfg(not(target_os = "windows"))]
fn install_request_blocker(_window: &tauri::WebviewWindow) {}

/// JNI entry point for the Android WebViewClient.
///
/// `shouldInterceptRequest` runs on a background thread for EVERY
/// subresource and must answer synchronously, so it cannot go through a
/// Tauri command (JS-facing, async, main-thread). It calls straight into
/// the engine here.
///
/// Fails open on every error path: a request we cannot evaluate is
/// allowed, because a false positive breaks the page while a false
/// negative only lets one ad through. The engine is already warmed on a
/// background thread at startup, so this is a hash lookup, not a build.
#[cfg(target_os = "android")]
#[no_mangle]
pub extern "system" fn Java_app_tamescroll_client_MainActivity_nativeShouldBlock(
    mut env: jni::JNIEnv,
    _class: jni::objects::JClass,
    url: jni::objects::JString,
    source_url: jni::objects::JString,
    resource_type: jni::objects::JString,
) -> jni::sys::jboolean {
    fn get(env: &mut jni::JNIEnv, s: &jni::objects::JString) -> Option<String> {
        env.get_string(s).ok().map(|v| v.into())
    }
    let (Some(u), Some(src), Some(ty)) = (
        get(&mut env, &url),
        get(&mut env, &source_url),
        get(&mut env, &resource_type),
    ) else {
        return 0;
    };
    // A panic must never cross the JNI boundary — it would abort the app
    // mid-page-load. Anything unexpected means "allow".
    std::panic::catch_unwind(|| blocks_request(&u, &src, &ty)).unwrap_or(false) as jni::sys::jboolean
}

/// The Android half of `synthetic_resource`: hand the interceptor the
/// bytes of a resource we answer ourselves, or null for the normal case.
///
/// Bytes rather than a String on purpose — the payload is a 16MB script
/// and a Java String would hold it as UTF-16, doubling it on a device
/// that has no memory to spare. Kotlin writes it to the cache directory
/// once and serves the file after that, so this crosses JNI a single
/// time per process.
#[cfg(target_os = "android")]
#[no_mangle]
pub extern "system" fn Java_app_tamescroll_client_MainActivity_nativeSyntheticResource<'a>(
    mut env: jni::JNIEnv<'a>,
    _class: jni::objects::JClass<'a>,
    url: jni::objects::JString<'a>,
) -> jni::sys::jbyteArray {
    use jni::objects::JObject;
    let null = JObject::null().into_raw();
    let Ok(u) = env.get_string(&url) else {
        return null;
    };
    let u: String = u.into();
    let Some(body) = std::panic::catch_unwind(|| synthetic_resource(&u)).unwrap_or(None) else {
        return null;
    };
    match env.byte_array_from_slice(body.as_bytes()) {
        Ok(arr) => arr.into_raw(),
        Err(_) => null,
    }
}

/// Rebuilds engine + surfaces from the current rule set (embedded +
/// OTA overrides). Called by ota.rs after a verified refresh; new page
/// loads pick the new data up immediately, already-rendered pages keep
/// their injected CSS until the next navigation.
pub(crate) fn rebuild_rules() {
    let built = Arc::new(rules::build_engine());
    *ENGINE.write().unwrap() = Some(built);
    rules::rebuild_surfaces();
}

#[derive(Serialize, Clone)]
pub struct Platform {
    id: &'static str,
    name: &'static str,
    url: &'static str,
    /// Brand colour, used by the launcher tile.
    tint: &'static str,
    /// Whether this platform is coherent once cleaned (its "cleaned
    /// core" — CONTEXT.md — survives). TikTok cleared that bar
    /// 2026-08-19 with Following + search + profiles as its core;
    /// Instagram stays not-ready until its rules are verified.
    ready: bool,
}

const PLATFORMS: &[Platform] = &[
    Platform {
        id: "youtube",
        name: "YouTube",
        url: "https://www.youtube.com/",
        tint: "#FF0033",
        ready: true,
    },
    Platform {
        id: "reddit",
        name: "Reddit",
        url: "https://www.reddit.com/",
        tint: "#FF4500",
        ready: true,
    },
    Platform {
        id: "x",
        name: "X",
        // /home lands on the timeline; our rules remove the For-you tab
        // there, leaving Following as the only one.
        url: "https://x.com/home",
        tint: "#71767B",
        ready: true,
    },
    Platform {
        id: "tiktok",
        name: "TikTok",
        // The cleaned core's front door: with For You hidden, "/" is an
        // intentionally empty room — Following is where a cleaned
        // TikTok session starts (owner decision 2026-08-19).
        url: "https://www.tiktok.com/following",
        tint: "#FE2C55",
        ready: true,
    },
    Platform {
        id: "instagram",
        name: "Instagram",
        url: "https://www.instagram.com/",
        tint: "#E1306C",
        ready: false,
    },
];

#[tauri::command]
fn platforms() -> Vec<Platform> {
    PLATFORMS.to_vec()
}

/// Launcher toggle changed: platform pages opened AFTER this pick up
/// the new mode (Android especially — its one webview re-reads the
/// state on every page load). Already-open pages keep their mode until
/// they navigate; live re-blur is a deliberate non-goal for now.
#[tauri::command]
fn set_gaze_mode(mode: String) {
    set_gaze_state(&mode);
}

/// Manual "check for rule updates now" from the launcher. Blocking
/// network work, so it runs off the main thread; returns a short status
/// line ("rules up to date" / "updated N rule file(s)") the launcher may
/// show inline — never as a nag.
#[tauri::command]
async fn refresh_rules() -> Result<String, String> {
    tauri::async_runtime::spawn_blocking(ota::refresh)
        .await
        .map_err(|e| e.to_string())?
}

/// In-app update check (owner ask 2026-08-23). Reads the signed app
/// manifest and reports whether a newer build exists; never installs.
/// The Android install path (MainActivity UpdateBridge) is what acts on
/// the returned apkUrl/sha256. Never errors to the UI — degrades to
/// "up to date" so the About pane can't nag.
#[tauri::command]
async fn app_update_check() -> appupdate::UpdateStatus {
    tauri::async_runtime::spawn_blocking(appupdate::check)
        .await
        .unwrap_or_else(|_| appupdate::check())
}

/// Same contract as `set_gaze_mode`, for the blur-strength picker:
/// already-open pages keep their radius until they navigate.
#[tauri::command]
fn set_blur_strength(px: u32) {
    set_blur_px(px);
}

/// Same contract again, for the launcher's gender declaration:
/// already-open pages keep their verdicts until they navigate.
#[tauri::command]
fn set_user_gender(gender: String) {
    set_user_gender_state(&gender);
}

/// Settings -> Filters user terms. Applies to pages opened after the
/// change, like every other gaze setting.
#[tauri::command]
fn set_user_terms(terms: Vec<String>) {
    set_user_terms_state(terms);
}

/// Build the CSS the engine says applies to this URL.
fn cosmetic_css(url: &str) -> String {
    let res = engine().url_cosmetic_resources(url);

    let mut css = String::new();

    if !res.hide_selectors.is_empty() {
        let mut selectors: Vec<&String> = res.hide_selectors.iter().collect();
        // Deterministic output keeps the injected script stable between
        // runs, which makes debugging a broken rule far easier.
        selectors.sort();
        // ONE RULE PER SELECTOR — never join them. In a comma-separated
        // selector list, a single invalid selector invalidates the whole
        // rule, and with thousands of upstream EasyList selectors in play
        // one bad apple silently turned off ALL hiding (Shorts came back;
        // caught by screenshot 2026-08-18). Per-selector rules contain
        // the damage to the one selector that is broken.
        for selector in selectors {
            css.push_str(selector);
            css.push_str(" { display: none !important; }\n");
        }
    }

    // `:style()` rules and other actioned filters arrive JSON-encoded.
    // Those expressible as plain CSS become rules here; the rest need a
    // JS-side evaluator we do not have yet, so they are skipped rather
    // than half-applied. Skipping a blur is survivable; a broken
    // selector that hides the player is not.
    let mut styled: Vec<(String, String)> = res
        .procedural_actions
        .iter()
        .filter_map(|encoded| serde_json::from_str::<ProceduralOrActionFilter>(encoded).ok())
        .filter_map(|filter| filter.as_css())
        .collect();
    styled.sort();
    for (selector, declarations) in styled {
        css.push_str(&format!("{selector} {{ {declarations} }}\n"));
    }

    css
}

/// Surface info the settings pane renders from, not a hardcoded copy of
/// `rules/*.txt`'s ids and labels. Always-on surfaces (ads) are excluded —
/// there is nothing to toggle, per VISION.md.
#[derive(Serialize, Clone)]
pub struct SurfaceInfo {
    id: String,
    label: String,
    /// The settings pane seeds a fresh install from this, once, and then
    /// never again — see `defaultShown` in main.ts.
    default_shown: bool,
}

#[tauri::command]
fn surfaces(id: String) -> Vec<SurfaceInfo> {
    rules::platform_surfaces(&id)
        .map(|surfaces| {
            surfaces
                .iter()
                .filter(|s| !s.always_on)
                .map(|s| SurfaceInfo {
                    id: s.id.to_string(),
                    label: s.label.to_string(),
                    default_shown: s.default_shown,
                })
                .collect()
        })
        .unwrap_or_default()
}

/// "N rules active" for the launcher status line: the engine's own
/// vendor-list hide selectors plus our own surface rules (default state —
/// nothing shown — matches the fully-cleaned experience every install
/// starts with).
#[tauri::command]
fn rules_summary() -> HashMap<String, usize> {
    let mut out = HashMap::new();
    for p in PLATFORMS {
        let engine_count = engine().url_cosmetic_resources(p.url).hide_selectors.len();
        let surface_count = rules::platform_surfaces(p.id)
            .map(|surfaces| surfaces.iter().map(|s| s.rules.len()).sum())
            .unwrap_or(0);
        out.insert(p.id.to_string(), engine_count + surface_count);
    }
    out
}

/// The script injected into every platform webview.
///
/// `scriptlets` is the engine's `injected_script` for this URL — the
/// scriptlets that strip ad data out of the page before its own scripts
/// read it (YouTube's player response, mainly; see VISION.md). It runs
/// first, and is wrapped in its own `try`/`catch` on top of the one each
/// individual scriptlet already gets from adblock-rust: a vendored
/// scriptlet that fails to parse must not be able to take the CSS
/// injection down with it.
///
/// The CSS block re-applies on SPA navigation because these sites rewrite
/// their own DOM without a page load, and Tauri's initialisation script is
/// not guaranteed to run before the site's own JavaScript on remote URLs.
/// Re-applying is cheap; missing a navigation is not.
fn injection_script(css: &str, scriptlets: &str) -> String {
    // JSON string, not a template literal: manual escaping missed `${`,
    // and one `${` in an OTA'd rule file would have been a SyntaxError
    // killing cosmetics AND scriptlets in one shot (review 2026-08-23
    // #7) — remotely triggerable once vendor lists update over the air.
    let escaped = serde_json::to_string(css).unwrap_or_else(|_| "\"\"".to_string());
    format!(
        r#"
(function () {{
  try {{
{scriptlets}
  }} catch (e) {{}}
}})();

(function () {{
  var CSS = {escaped};
  var STYLE_ID = "tamescroll-rules";

  function apply() {{
    if (document.getElementById(STYLE_ID)) return;
    var head = document.head || document.documentElement;
    if (!head) return;
    var el = document.createElement("style");
    el.id = STYLE_ID;
    el.textContent = CSS;
    head.appendChild(el);
  }}

  apply();
  document.addEventListener("DOMContentLoaded", apply);

  // These sites navigate without a page load. Re-assert after each one.
  ["pushState", "replaceState"].forEach(function (name) {{
    var original = history[name];
    history[name] = function () {{
      var result = original.apply(this, arguments);
      setTimeout(apply, 0);
      return result;
    }};
  }});
  window.addEventListener("popstate", function () {{ setTimeout(apply, 0); }});

  // Last resort: if the site tears our style out, put it back.
  // try/catch is load-bearing: at document-start documentElement can be
  // null, and the uncaught observe() throw silently killed EVERYTHING
  // after this IIFE in the same script (found 2026-08-24 when the home
  // pill — the first code ever appended after this — never ran).
  try {{
    new MutationObserver(function () {{ apply(); }})
      .observe(document.documentElement, {{ childList: true, subtree: false }});
  }} catch (e) {{
    document.addEventListener("DOMContentLoaded", function () {{
      try {{
        new MutationObserver(function () {{ apply(); }})
          .observe(document.documentElement, {{ childList: true, subtree: false }});
      }} catch (e2) {{}}
    }});
  }}
}})();

(function () {{
  // Home pill (owner ask 2026-08-24): a small fixed control back to the
  // tamescroll launcher/settings from any platform page. Never on the
  // launcher itself. Navigation target is the launcher origin: Android's
  // single webview genuinely navigates there (same URL the Back handler
  // loads); desktop platform windows intercept it in on_navigation and
  // focus the launcher window instead (see open_platform).
  window.__TS_HOME_IIFE__ = "entered";
  if (/(^|\.)tauri\.localhost$/.test(location.hostname)) return;
  var HOME_ID = "tamescroll-home";
  function ensureHome() {{
    if (document.getElementById(HOME_ID)) return;
    var body = document.body;
    if (!body) return;
    var b = document.createElement("button");
    b.id = HOME_ID;
    b.type = "button";
    b.textContent = "ts";
    b.setAttribute("aria-label", "tamescroll settings");
    b.style.cssText =
      "position:fixed;left:10px;bottom:14px;z-index:2147483645;" +
      "width:34px;height:34px;border-radius:50%;border:none;" +
      "background:rgba(15,17,21,.62);color:#e8e6e3;" +
      "font:600 13px system-ui;opacity:.55;cursor:pointer;" +
      "pointer-events:auto;backdrop-filter:blur(6px);";
    b.addEventListener("mouseenter", function () {{ b.style.opacity = "1"; }});
    b.addEventListener("mouseleave", function () {{ b.style.opacity = ".55"; }});
    b.addEventListener("click", function (e) {{
      e.stopPropagation();
      location.href = "http://tauri.localhost/";
    }});
    body.appendChild(b);
  }}
  ensureHome();
  document.addEventListener("DOMContentLoaded", ensureHome);
  setInterval(ensureHome, 3000);
}})();
"#
    )
}

/// Root domain a platform's rules key on: the platform URL's host minus
/// a leading `www.` — `youtube.com`, `reddit.com`, `x.com`.
#[cfg_attr(not(target_os = "android"), allow(dead_code))]
fn platform_root(url: &str) -> &str {
    let host = url
        .split("://")
        .nth(1)
        .unwrap_or(url)
        .split('/')
        .next()
        .unwrap_or(url);
    host.strip_prefix("www.").unwrap_or(host)
}

/// Android-only injection (docs/android-research.md, emulator findings
/// 2026-08-18): tapping a tile there does NOT create a new window — it
/// navigates the launcher's own single WebView, so a per-window
/// `initialization_script` never reaches the platform page at all (this
/// is how the Shorts tab survived two builds). A Tauri *plugin* script
/// applies to every webview and re-runs on every page load, so this one
/// dispatches on `location.host` at runtime: our surface rules for the
/// matching platform, defaults only (everything hidden, no blur, no
/// gaze — Android settings/mode plumbing is a follow-up, as are the
/// vendor cosmetic lists and scriptlets, which need the warmed engine
/// and can't block app startup).
#[cfg_attr(not(target_os = "android"), allow(dead_code))]
fn universal_injection_script() -> String {
    let mut branches = String::new();
    for p in PLATFORMS {
        if rules::platform_surfaces(p.id).is_none() {
            continue;
        }
        let css = surfaces_css(p.id, &[]);
        // JSON string, not a template literal — same `${` hazard as
        // injection_script (review 2026-08-23 #7).
        let escaped = serde_json::to_string(&css).unwrap_or_else(|_| "\"\"".to_string());
        let root = platform_root(p.url);
        branches.push_str(&format!(
            "    if (h === \"{root}\" || h.endsWith(\".{root}\")) return {escaped};\n"
        ));
    }

    // Debug builds carry boundary markers so `adb logcat` (Tauri/Console)
    // shows exactly how far the injection pipeline got on-device:
    // enter -> host -> matched/no-match -> applied. Compiled out of
    // release builds.
    let trace = if cfg!(debug_assertions) {
        r#"var TS_LOG = function (m) { try { console.log("TS_UNIVERSAL " + m); } catch (e) {} };"#
    } else {
        r#"var TS_LOG = function () {};"#
    };

    format!(
        r#"
(function () {{
  {trace}
  if (window.__TS_UNIVERSAL__) {{ TS_LOG("skip: already ran"); return; }}
  window.__TS_UNIVERSAL__ = 1;

  var h = location.host;
  TS_LOG("enter host=" + h);
  var CSS = (function () {{
{branches}    return "";
  }})();
  if (!CSS) {{ TS_LOG("no-match host=" + h); return; }}
  TS_LOG("matched host=" + h + " css_len=" + CSS.length);

  var STYLE_ID = "tamescroll-rules";

  function apply() {{
    if (document.getElementById(STYLE_ID)) return;
    var head = document.head || document.documentElement;
    if (!head) return;
    var el = document.createElement("style");
    el.id = STYLE_ID;
    el.textContent = CSS;
    head.appendChild(el);
  }}

  apply();
  document.addEventListener("DOMContentLoaded", apply);

  ["pushState", "replaceState"].forEach(function (name) {{
    var original = history[name];
    history[name] = function () {{
      var result = original.apply(this, arguments);
      setTimeout(apply, 0);
      return result;
    }};
  }});
  window.addEventListener("popstate", function () {{ setTimeout(apply, 0); }});

  new MutationObserver(function () {{ apply(); }})
    .observe(document.documentElement, {{ childList: true, subtree: false }});

  setTimeout(function () {{
    TS_LOG(
      "t+5s style_present=" + !!document.getElementById(STYLE_ID) +
      " readyState=" + document.readyState
    );
  }}, 5000);
}})();
"#
    )
}

/// The plugin carrying `universal_injection_script` into every webview.
/// Android-only: on desktop each platform window gets its own richer
/// script (vendor cosmetics, scriptlets, mode and shown prefs) and this
/// would only double up.
#[cfg(target_os = "android")]
fn injection_plugin<R: tauri::Runtime>() -> tauri::plugin::TauriPlugin<R> {
    tauri::plugin::Builder::new("ts-inject")
        .js_init_script(universal_injection_script())
        // Gaze rides page-load events because the mode is runtime state:
        // eval at Started so blur-first holds (the document exists but
        // nothing has painted), again at Finished as the fallback when
        // Started raced document creation — the style-id guard makes the
        // second eval a no-op.
        .on_page_load(|webview, payload| {
            // Rules first (scriptlets want to beat page scripts), gaze
            // second. Both guarded, both eval at Started and Finished —
            // see the CSP note above page_load_gaze_script for why the
            // Finished eval cannot be a cheap string fallback.
            if let Some(js) = page_load_rules_script(payload.url().as_str()) {
                let _ = webview.eval(&js);
            }
            if let Some(js) = page_load_gaze_script(payload.url().as_str(), gaze_state()) {
                let _ = webview.eval(&js);
            }
        })
        .build()
}

// Android: everything after the navigate-and-return block is
// desktop-only builder code the compiler sees as unreachable there.
#[cfg_attr(target_os = "android", allow(unreachable_code, unused_variables))]
#[tauri::command]
async fn open_platform(
    app: tauri::AppHandle,
    id: String,
    mode: String,
    strength: u32,
    gender: String,
    shown: Vec<String>,
) -> Result<(), String> {
    let platform = PLATFORMS
        .iter()
        .find(|p| p.id == id)
        .ok_or_else(|| format!("unknown platform: {id}"))?;

    #[cfg(debug_assertions)]
    eprintln!("open_platform id={id}");

    // Keep the Rust-side gaze state current: Android page loads read it
    // (see injection_plugin), and it costs nothing on desktop. Strength
    // rides along for the same reason (and dodges the same fire-and-
    // forget race the mode parameter exists for).
    set_gaze_state(&mode);
    set_blur_px(strength);
    set_user_gender_state(&gender);
    set_shown_state(shown.clone());

    let url: tauri::Url = platform
        .url
        .parse()
        .map_err(|_| format!("bad platform url: {}", platform.url))?;

    // Android is a single-webview platform: never create or focus a
    // second window. The old label-reuse guard called set_focus() and
    // returned Ok — visually a no-op, so every tile tap after the first
    // "succeeded" silently (probe evidence 2026-08-18, spikes/
    // logcat-probe7.log: JS "open ok" with no visible effect). Navigate
    // the main webview in place instead; cosmetic injection rides the
    // ts-inject plugin script, which fires on every page load.
    #[cfg(target_os = "android")]
    {
        let main = app
            .get_webview_window("main")
            .ok_or_else(|| "no main webview".to_string())?;
        let nav = main.navigate(url);
        #[cfg(debug_assertions)]
        eprintln!("open_platform navigate main -> {nav:?}");
        return nav.map_err(|e| e.to_string());
    }

    // Desktop: re-opening a platform whose window is still open just
    // focuses it — a second Builder::build on a taken label would error.
    #[cfg(not(target_os = "android"))]
    if let Some(existing) = app.get_webview_window(platform.id) {
        existing.set_focus().map_err(|e| e.to_string())?;
        return Ok(());
    }

    let mode = gaze_mode(&mode);
    let resources = engine().url_cosmetic_resources(platform.url);
    let script = injection_script(
        &page_css(platform.url, platform.id, mode == "blur", &shown),
        &resources.injected_script,
    );

    // The gaze bundle does NOT ride initialization_script here: on
    // Windows the >1MB combined script silently loses its tail — the
    // early CSS IIFE of the very same string ran while the appended
    // bundle left no trace (probe28/29, 2026-08-19; composed script
    // node --check clean, so not a syntax break). Smart mode instead
    // evals per page load, the exact delivery already proven on
    // Android with this same 1.6MB payload. Side effect, and a
    // deliberate one: desktop navigations now read the CURRENT gaze
    // state like Android does, instead of the mode baked at window
    // creation.
    // Home pill (injection_script) navigates to the launcher origin;
    // on desktop that must FOCUS the launcher window, not render a
    // second launcher inside the platform window — intercept and cancel.
    let home_app = app.clone();
    let built = WebviewWindowBuilder::new(&app, platform.id, WebviewUrl::External(url))
        .title(platform.name)
        .inner_size(1200.0, 860.0)
        .initialization_script(&script)
        .on_navigation(move |url| {
            if url.host_str() == Some("tauri.localhost") {
                if let Some(main) = home_app.get_webview_window("main") {
                    let _ = main.set_focus();
                }
                return false;
            }
            true
        })
        .on_page_load(|webview, payload| {
            if let Some(js) = page_load_gaze_script(payload.url().as_str(), gaze_state()) {
                let _ = webview.eval(&js);
            }
        })
        .build();
    if let Ok(w) = &built {
        // Ad/tracker network blocking. Installed per platform window,
        // right after creation, so it is live before the first
        // subresource of the first page load.
        install_request_blocker(w);
    }
    #[cfg(debug_assertions)]
    eprintln!(
        "open_platform build id={} -> {:?}",
        platform.id,
        built.as_ref().map(|_| ()).map_err(|e| e.to_string())
    );
    built.map_err(|e| e.to_string())?;

    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Warm the engine off the critical path: building it from the full
    // vendored list set takes on the order of a second, and nothing about
    // startup needs it until the first `open_platform` call.
    std::thread::spawn(|| {
        #[cfg(debug_assertions)]
        let started = std::time::Instant::now();
        engine();
        #[cfg(debug_assertions)]
        eprintln!("adblock engine warmed in {:?}", started.elapsed());
    });

    let builder = tauri::Builder::default().plugin(tauri_plugin_opener::init());

    // Android: the single-WebView model means per-window injection never
    // fires — the plugin script is the only reliable delivery there.
    #[cfg(target_os = "android")]
    let builder = builder.plugin(injection_plugin());

    builder
        .setup(|app| {
            // Rules OTA: restore the cached rule set, then keep it fresh
            // (launch + every 24h, silent). Off the main thread — init
            // does disk IO and its loop does network.
            let cache_dir = app
                .path()
                .app_data_dir()
                .map(|d| d.join("rules-cache"))
                .ok();
            if let Some(dir) = cache_dir {
                std::thread::spawn(move || ota::init(dir));
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            platforms,
            open_platform,
            rules_summary,
            surfaces,
            set_gaze_mode,
            set_blur_strength,
            set_user_gender,
            set_user_terms,
            refresh_rules,
            app_update_check,
            should_block_request
        ])
        .run(tauri::generate_context!())
        .expect("error while running tamescroll");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The gap the owner hit 2026-08-25: the engine held EasyList,
    /// EasyPrivacy and the uBO lists all along and was never asked about
    /// a single network request. These four URLs were MEASURED reaching
    /// the network from one YouTube watch page in the dev app.
    #[test]
    fn blocks_the_ad_requests_that_were_measured_getting_through() {
        let page = "https://www.youtube.com/watch?v=E4lnTIJaz-g";
        for (url, kind) in [
            ("https://googleads.g.doubleclick.net/pagead/id", "image"),
            ("https://static.doubleclick.net/instream/ad_status.js", "script"),
            (
                "https://googleads.g.doubleclick.net/pagead/viewthroughconversion/962985656/",
                "image",
            ),
        ] {
            assert!(
                blocks_request(url, page, kind),
                "must block ad request: {url}"
            );
        }
    }

    /// The other half, and the one that actually matters: over-blocking
    /// breaks the player, and a broken player is worse than an ad.
    #[test]
    fn never_blocks_the_page_or_the_player_itself() {
        let page = "https://www.youtube.com/watch?v=E4lnTIJaz-g";
        for (url, kind) in [
            ("https://www.youtube.com/watch?v=E4lnTIJaz-g", "document"),
            ("https://www.youtube.com/youtubei/v1/player", "xhr"),
            ("https://i.ytimg.com/vi/E4lnTIJaz-g/hqdefault.jpg", "image"),
            ("https://rr3---sn-abc.googlevideo.com/videoplayback?x=1", "media"),
            ("https://www.youtube.com/s/player/base.js", "script"),
        ] {
            assert!(
                !blocks_request(url, page, kind),
                "must NOT block: {url}"
            );
        }
    }

    /// Our own IPC and launcher can never serve an ad, and a false
    /// positive there bricks the app rather than degrading it.
    #[test]
    fn never_blocks_our_own_surfaces() {
        assert!(!blocks_request("tauri://localhost/index.html", "tauri://localhost", "document"));
        assert!(!blocks_request("http://tauri.localhost/main.js", "http://tauri.localhost", "script"));
    }

    /// A malformed URL must degrade to "allow", not panic: this runs
    /// inside a page load on every request.
    #[test]
    fn a_malformed_url_is_allowed_not_a_panic() {
        assert!(!blocks_request("not a url at all", "also not a url", "script"));
    }

    /// Owner report 2026-08-20 (first real-phone test): "ad blocking does
    /// not work at all in the mobile app." Root cause: Android's only
    /// injection was the universal plugin script, which carries ONLY our
    /// surfaces CSS — never the engine's cosmetic ad-hiding, never the
    /// scriptlets. This pins the fix: every platform page load must get
    /// the full rules payload, current `shown` prefs included, and it
    /// must be safe to eval twice (Started + Finished).
    #[test]
    fn page_load_rules_script_carries_full_ad_blocking() {
        set_shown_state(Vec::new());
        let js = page_load_rules_script("https://m.youtube.com/").expect("rules for m.youtube");
        assert!(js.contains("tamescroll-rules"), "cosmetic style id missing");
        assert!(
            js.len() > surfaces_css("youtube", &[]).len() + 1000,
            "must carry engine cosmetics beyond our surfaces ({} bytes)",
            js.len()
        );
        assert!(js.contains("__TS_RULES__"), "needs a re-entry guard for double eval");
        assert!(
            js.contains("removeChild(ts_u)"),
            "must replace the universal surfaces-only sheet (same style id) or the full CSS never lands"
        );

        // Desktop-host URL must work the same way (pre-redirect load).
        assert!(page_load_rules_script("https://www.youtube.com/").is_some());

        // The current bring-back prefs must reach the payload: a shown
        // surface's selectors disappear from it.
        set_shown_state(vec!["shorts".into()]);
        let js_shown = page_load_rules_script("https://www.youtube.com/").expect("rules");
        assert!(
            !js_shown.contains("ytd-reel-shelf-renderer"),
            "shown surface must not be hidden by the page-load payload"
        );
        set_shown_state(Vec::new());

        // Non-platform hosts get nothing.
        assert!(page_load_rules_script("https://accounts.google.com/").is_none());
    }

    /// A hard navigation to a watch page must drop the EMBEDDED
    /// streamingData, not just the ad fields.
    ///
    /// Pruning only the ad fields kills the ad but leaves YouTube's SABR
    /// backoff attached to the embedded stream — measured 24-37s to first
    /// frame, i.e. the user waits out the ad and sees black instead. With
    /// no stream embedded the player must issue a client-side
    /// /youtubei/v1/player request, which the isInlinePlaybackNoAd rule
    /// reshapes into a stream carrying neither ad nor backoff (measured
    /// 8.3s). Dropping this argument silently restores the 30-second
    /// stall, and nothing else in the suite would notice.
    #[test]
    fn watch_page_forces_a_fresh_player_request() {
        let js = engine()
            .url_cosmetic_resources("https://www.youtube.com/watch?v=DD54J5kecpg")
            .injected_script;
        let call = js
            .lines()
            .find(|l| l.starts_with("trustedPruneWindowJson("))
            .expect("the inline-JSON pruner must be emitted for a watch page");
        assert!(
            call.contains("\"streamingData\""),
            "watch pages must drop the embedded streamingData or the SABR              backoff survives the ad: {call}"
        );
        for field in ["adSlots", "adPlacements", "playerAds"] {
            assert!(call.contains(field), "{field} must still be pruned: {call}");
        }
        // The request-shaper is the other half: without it the fresh
        // /player request just serves the ad again.
        assert!(
            js.contains("isInlinePlaybackNoAd"),
            "the ad-free-stream request shaper must ship alongside"
        );
    }

    /// Proves the two halves of in-app ad blocking VISION.md describes are
    /// actually wired: cosmetic hiding (already worked) and scriptlet
    /// injection (the point of this change). A regression here means
    /// either the vendored lists didn't load or the scriptlet resources
    /// didn't — see rules.rs and rules/vendor/README.md.
    #[test]
    fn youtube_gets_hide_selectors_and_a_scriptlet_injection() {
        let resources =
            engine().url_cosmetic_resources("https://www.youtube.com/watch?v=aqz-KE-bpKQ");
        assert!(
            !resources.injected_script.is_empty(),
            "expected a non-empty scriptlet injection for a YouTube watch page — \
             this is what strips ad data out of the player response"
        );
        // Our clean-room scriptlets, resolved by name from the filter
        // lists: the initial-load pin and the SPA-navigation strippers.
        for needle in [
            "setConstant(",
            "trustedReplaceFetchResponse(",
            "trustedReplaceXhrResponse(",
        ] {
            assert!(
                resources.injected_script.contains(needle),
                "expected {needle:?} in the YouTube injection — a scriptlet \
                 name stopped resolving (see rules.rs SCRIPTLETS)"
            );
        }

        // Home-page hide selectors used to come only from youtube.txt's
        // own rules inside the engine; Phase 3 moved those out into our
        // own surfaces (see rules.rs), so this now goes through the same
        // page_css() path the app actually injects — the assertion (some
        // hide selectors reach a YouTube home page) is unchanged.
        let css = page_css("https://www.youtube.com/", "youtube", false, &[]);
        assert!(
            css.contains("display: none !important;"),
            "expected cosmetic hide selectors for the YouTube home page"
        );
    }

    /// The home pill (owner ask 2026-08-24) rides the injection wrapper
    /// to every platform page on both OSes, guarded off the launcher's
    /// own origin. Its click target is the launcher origin the desktop
    /// on_navigation intercept keys on — the two strings must agree.
    
    #[test]
    fn injection_script_carries_the_home_pill() {
        let js = injection_script("body { color: red }", "");
        assert!(js.contains("tamescroll-home"), "home pill element missing");
        assert!(
            js.contains(r#"location.href = "http://tauri.localhost/""#),
            "home pill must navigate to the launcher origin (desktop \
             on_navigation and Android launcherUrl both key on it)"
        );
        assert!(
            js.contains("tauri\\.localhost$/.test(location.hostname)"),
            "launcher-origin guard missing — the pill would render on the launcher itself"
        );
    }

    /// Our own platform rules must survive the trip through the parser
    /// and into the assembled page CSS — a selector that fails to parse
    /// is silently dropped, and this is where that would surface. Moved
    /// off the raw engine call in Phase 3 (docs/plan.md settings pane):
    /// these rules no longer live in the engine's FilterSet, they live in
    /// rules.rs's surface parser and get assembled by page_css().
    #[test]
    fn reddit_and_x_rules_survive_parsing() {
        let reddit_css = page_css("https://www.reddit.com/", "reddit", false, &[]);
        assert!(
            reddit_css.contains("shreddit-ad-post"),
            "reddit.txt's ad rules should be present for reddit.com"
        );

        let x_css = page_css("https://x.com/home", "x", false, &[]);
        assert!(
            !x_css.is_empty(),
            "x.txt rules should produce CSS for x.com"
        );
    }

    /// The launcher toggle must actually change what gets injected —
    /// this is the wire between the UI and the page.
    #[test]
    fn blur_toggle_reaches_the_injected_stylesheet() {
        let off = page_css("https://www.youtube.com/", "youtube", false, &[]);
        let on = page_css("https://www.youtube.com/", "youtube", true, &[]);
        assert!(!off.contains("blur("), "blur css must be absent when off");
        assert!(on.contains("blur("), "blur css must be present when on");
    }

    /// The Android tap highlight must be killed on EVERY platform page,
    /// in every mode — the owner's screenshot was m.youtube with blur on,
    /// but the teal rectangle is a WebView default and appears wherever a
    /// page is tapped, so a rule that only ships in one mode or on one
    /// platform would leave it visible somewhere.
    #[test]
    fn tap_highlight_is_killed_on_every_platform_page() {
        for (url, id) in [
            ("https://www.youtube.com/", "youtube"),
            ("https://m.youtube.com/", "youtube"),
            ("https://www.reddit.com/", "reddit"),
            ("https://x.com/home", "x"),
        ] {
            for blur in [false, true] {
                let css = page_css(url, id, blur, &[]);
                assert!(
                    css.contains("-webkit-tap-highlight-color: transparent"),
                    "tap highlight override missing for {id} blur={blur}"
                );
            }
        }
    }

    /// Bring-back settings (docs/plan.md Phase 3): showing one surface
    /// must remove only that surface's selectors from the injected CSS —
    /// other surfaces (here: home) must be untouched.
    #[test]
    fn showing_one_surface_hides_only_that_surface() {
        let default_css = page_css("https://www.youtube.com/", "youtube", false, &[]);
        assert!(
            default_css.contains("ytd-reel-shelf-renderer"),
            "shorts selectors should be present by default"
        );
        assert!(
            default_css.contains("ytd-rich-grid-renderer"),
            "home selectors should be present by default"
        );

        let shorts_shown = page_css(
            "https://www.youtube.com/",
            "youtube",
            false,
            &["shorts".to_string()],
        );
        assert!(
            !shorts_shown.contains("ytd-reel-shelf-renderer"),
            "shorts selectors must be absent once shorts is shown"
        );
        assert!(
            shorts_shown.contains("ytd-rich-grid-renderer"),
            "home selectors must remain when only shorts is shown"
        );
    }

    /// VISION.md: ad-hiding is never user-toggleable. Even if the
    /// frontend somehow sent "ads" in `shown` (it never offers the
    /// option — see the `surfaces` command), the always_on surface must
    /// stay hidden.
    #[test]
    fn always_on_ads_surface_cannot_be_shown() {
        let css = page_css(
            "https://www.youtube.com/",
            "youtube",
            false,
            &["ads".to_string()],
        );
        assert!(
            css.contains("ytd-ad-slot-renderer"),
            "the always-on ads surface must stay hidden even when 'shown' asks for it"
        );
    }

    /// Android gaze delivery (plugin on_page_load): the page-load script
    /// must exist exactly when a platform page meets an active mode, carry
    /// the right payload per mode, and map mobile hosts to their platform.
    #[test]
    fn page_load_gaze_script_dispatches_on_mode_and_host() {
        // A non-platform host, or a platform without a blur sheet:
        // nothing to eval, in any mode.
        assert!(page_load_gaze_script("https://accounts.google.com/", "blur").is_none());
        assert!(page_load_gaze_script("https://www.instagram.com/", "blur").is_none());
        assert!(page_load_gaze_script("https://www.instagram.com/", "off").is_none());
        assert!(page_load_gaze_script("http://tauri.localhost/", "smart").is_none());

        // Off still boots Stage B for the compulsory NSFW-removal tier
        // (handoff decision #1) — mode "off" baked in, no Stage A sheet.
        let js = page_load_gaze_script("https://m.youtube.com/", "off").expect("off script");
        assert!(js.contains("__TS_GAZE_MODE = \"off\""), "off must boot the compulsory tier");
        assert!(!js.contains("ts-gaze-blur"), "off must not ship the Stage A sheet");

        // Blur mode injects the guarded style AND the Stage B boot (the
        // bundle only runs NSFW removal in blur mode); the mobile host
        // maps to the same platform as the desktop one.
        for url in ["https://www.youtube.com/", "https://m.youtube.com/"] {
            let js = page_load_gaze_script(url, "blur").expect("blur script for youtube");
            assert!(js.contains("ts-gaze-blur"), "style-id guard missing");
            assert!(js.contains("blur("), "blur css payload missing");
            assert!(
                js.contains("__TS_GAZE_MODE = \"blur\""),
                "blur mode must boot the compulsory tier"
            );
            assert!(
                js.contains("--ts-blur:"),
                "blur payload must define the strength variable"
            );
        }

        // Smart mode boots Stage B and ships NO Stage A sheet — those
        // selectors have no class hook, so Stage B's unblur could never
        // win against them (the mode would collapse into blur-all).
        let js = page_load_gaze_script("https://www.reddit.com/", "smart").expect("smart script");
        assert!(js.contains("__TS_GAZE_MODE"), "smart mode must boot Stage B");
        assert!(
            !js.contains("ts-gaze-blur"),
            "smart mode must not ship the Stage A sheet"
        );
        assert!(
            js.contains("__TS_GAZE_BUNDLE__"),
            "the bundle wrapper must be re-entry guarded"
        );

        // Subdomain hosts the universal script matches must blur too —
        // the two matchers agreeing is the contract (old.reddit.com had
        // hide-CSS but sharp images before this).
        assert!(page_load_gaze_script("https://old.reddit.com/", "blur").is_some());
        assert!(page_load_gaze_script("https://m.youtube.com:443/", "blur").is_some());
        assert!(page_load_gaze_script("https://notyoutube.com/", "blur").is_none());
        assert!(page_load_gaze_script("https://www.tiktok.com/following", "blur").is_some());
        assert!(page_load_gaze_script("https://www.tiktok.com/", "smart").is_some());

        // Unknown modes normalise to off (gaze_mode contract) — which
        // now still means the compulsory tier boots on platform hosts.
        let js = page_load_gaze_script("https://x.com/home", "nonsense").expect("normalised off");
        assert!(js.contains("__TS_GAZE_MODE = \"off\""));
    }

    /// The Rust-side mode mirror the Android page loads read.
    #[test]
    fn gaze_state_round_trips_and_normalises() {
        set_gaze_state("smart");
        assert_eq!(gaze_state(), "smart");
        set_gaze_state("garbage");
        assert_eq!(gaze_state(), "off");
        set_gaze_state("blur");
        assert_eq!(gaze_state(), "blur");
        set_gaze_state("off");
        assert_eq!(gaze_state(), "off");
    }

    /// The gender declaration follows the same lifecycle as mode and
    /// strength: launcher sets, Rust holds, the smart boot script bakes
    /// it in as __TS_GAZE_GENDER. Unknown values must land on "unset"
    /// (bundle then covers any face — fail-safe), never leak through.
    #[test]
    fn user_gender_round_trips_and_reaches_the_smart_boot_script() {
        set_user_gender_state("man");
        assert_eq!(user_gender(), "man");
        let js = gaze_script("smart");
        assert!(js.contains("__TS_GAZE_GENDER = \"man\""));

        set_user_gender_state("woman");
        let js = gaze_script("smart");
        assert!(js.contains("__TS_GAZE_GENDER = \"woman\""));

        set_user_gender_state("attack-string\" ;alert(1);");
        assert_eq!(user_gender(), "unset");
        let js = gaze_script("smart");
        assert!(js.contains("__TS_GAZE_GENDER = \"unset\""));

        set_user_gender_state("unset");
    }

    /// User filter terms reach the smart boot script as a JSON array,
    /// sanitised (trimmed, bounded) so a hostile term can't break out
    /// of the script string.
    #[test]
    fn user_terms_reach_the_smart_boot_script_sanitised() {
        set_user_terms_state(vec!["  crypto  ".into(), "".into(), "a\"b".into()]);
        let js = gaze_script("smart");
        assert!(js.contains("__TS_USER_TERMS"));
        assert!(js.contains("[\"crypto\",\"a\\\"b\"]"), "json: {}", user_terms_json());
        set_user_terms_state(Vec::new());
        assert!(gaze_script("smart").contains("__TS_USER_TERMS = []"));
    }

    /// The strength preset follows the same lifecycle as the mode:
    /// launcher picks, Rust holds, injection reads. Unknown values must
    /// land on the medium default, never 0px.
    #[test]
    fn blur_strength_round_trips_and_reaches_every_blur_consumer() {
        set_blur_px(28);
        assert_eq!(blur_px(), 28);
        set_blur_px(999);
        assert_eq!(blur_px(), 16, "unknown strength must normalise to medium");
        set_blur_px(8);
        assert_eq!(blur_px(), 8);

        // The vars rule carries both radii (Stage A + Stage B's heavier one).
        let vars = blur_vars_css(8);
        assert!(vars.contains("--ts-blur: 8px"));
        assert!(vars.contains("--ts-blur-strong: 12px"));

        // Stage A sheets resolve through the variable...
        for id in BLUR_PLATFORMS {
            let css = blur_css(id);
            assert!(
                css.contains("var(--ts-blur"),
                "blur css for {id} should resolve its radius via --ts-blur"
            );
        }
        // ...and the page-level CSS ships the definition alongside them.
        let css = page_css("https://www.youtube.com/", "youtube", true, &[]);
        assert!(css.contains("--ts-blur:"), "page_css(blur) must define --ts-blur");

        // Smart mode has no stylesheet of its own, so its wrapper sets
        // the variables inline for Stage B's class styles.
        let smart = gaze_script("smart");
        assert!(smart.contains("--ts-blur-strong"));

        set_blur_px(16);
    }

    /// Stage A blur CSS (docs/plan.md Phase 4) must actually blur something
    /// on every platform, and must never list the watch-page player as a
    /// target — that is the one surface the module exists to leave alone.
    #[test]
    fn blur_css_is_present_and_never_targets_the_player() {
        for id in BLUR_PLATFORMS {
            let css = blur_css(id);
            assert!(!css.is_empty(), "blur css for {id} must not be empty");
            assert!(
                css.contains("blur("),
                "blur css for {id} should contain a blur() filter"
            );
        }

        assert!(
            !blur_css("youtube").contains("#movie_player video"),
            "the YouTube blur css must never target #movie_player video — \
             the video the user is watching must never blur"
        );

        // Owner call 2026-08-19: TikTok blurs EVERYTHING — all img +
        // video site-wide (first report: /following uncovered; second:
        // profile still partial). Pin the blanket coverage and the
        // video-detail red-line guard.
        let tiktok = blur_css("tiktok");
        assert!(
            tiktok.contains("img,\nvideo {"),
            "TikTok blur css must blur all media site-wide"
        );
        assert!(
            tiktok.contains(r#"[id^="main-content-video_detail"] video"#)
                && tiktok.contains("filter: none !important"),
            "TikTok blur css must keep the opened video sharp (red line)"
        );
    }

    /// Owner report 2026-08-18: search results were still full of
    /// "People also search for" / "Channels new to you" wedges. The
    /// fix lives in rules/youtube.txt — this pins those selectors all
    /// the way through to the CSS a search page receives. Goes through
    /// page_css() rather than the bare engine call since Phase 3 moved
    /// these selectors out of the engine and into our own surface rules
    /// (rules.rs) — same assertions, different plumbing.
    #[test]
    fn youtube_search_inserts_are_hidden_in_the_injected_css() {
        let css = page_css(
            "https://www.youtube.com/results?search_query=minecraft",
            "youtube",
            false,
            &[],
        );
        for sel in [
            "ytd-search-pyv-renderer",
            "ytd-search ytd-shelf-renderer",
            "ytd-search ytd-horizontal-card-list-renderer",
            "ytd-universal-watch-card-renderer",
        ] {
            assert!(
                css.contains(sel),
                "expected search-insert selector {sel:?} in the injected CSS"
            );
        }
    }

    /// The Android delivery path (single WebView, plugin script) must
    /// carry every platform's rules and dispatch on host — including the
    /// m.youtube.com rules that the emulator proved are the ones Android
    /// actually needs.
    #[test]
    fn universal_script_carries_all_platforms_and_dispatches_on_host() {
        let script = universal_injection_script();
        for marker in [
            "\"youtube.com\"",
            "\"reddit.com\"",
            "\"x.com\"",
            "ytm-pivot-bar-item-renderer",
            "ytd-browse[page-subtype=\\\"home\\\"]",
            "shreddit-app",
            "__TS_UNIVERSAL__",
        ] {
            let found = script.contains(marker)
                || script.contains(&marker.replace("\\\"", "\""));
            assert!(found, "expected {marker:?} in the universal script");
        }
    }

    /// Emulator lesson 2026-08-18: Android's UA redirect moves the
    /// YouTube window to m.youtube.com AFTER injection, so the mobile
    /// (ytm-*) rules must ship in the window's CSS even though the
    /// platform URL says www.youtube.com — host-filtering them out is
    /// how the Shorts tab survived on the first Android run.
    #[test]
    fn mobile_youtube_rules_ship_in_the_desktop_window_css() {
        let css = page_css("https://www.youtube.com/", "youtube", false, &[]);
        assert!(
            css.contains("ytm-pivot-bar-item-renderer"),
            "m.youtube.com Shorts-tab rule must be in the injected CSS"
        );
        assert!(
            css.contains("ytm-reel-shelf-renderer"),
            "m.youtube.com Shorts-shelf rule must be in the injected CSS"
        );
    }

    /// Stage B (gaze-research.md): the generated runtime must actually be
    /// present in the binary and non-trivial — an empty or missing bundle
    /// would mean "smart" silently degrades to doing nothing.
    #[test]
    fn gaze_bundle_is_non_empty() {
        assert!(
            !GAZE_INIT_JS.is_empty(),
            "app/src-tauri/gaze-init.js is empty or missing — run `npm run build:gaze` in app/"
        );
    }

    /// The launcher's mode picker must actually change what gets
    /// injected — this is the wire between the "Smart" option and the
    /// page, same role as blur_toggle_reaches_the_injected_stylesheet
    /// plays for Stage A.
    #[test]
    fn smart_mode_injects_the_gaze_bundle_with_its_marker() {
        let script = gaze_script("smart");
        assert!(
            !script.is_empty(),
            "smart mode must inject a non-empty gaze script"
        );
        assert!(
            script.contains("__TS_GAZE_BUNDLE__"),
            "expected the gaze bundle's minification-proof marker in the \
             smart-mode injection — see gaze/src/init-entry.js"
        );
        assert!(
            script.contains("window.__TS_GAZE_MODE = \"smart\";"),
            "smart mode must set window.__TS_GAZE_MODE before the bundle runs"
        );
    }

    /// Compulsory tier (handoff decision #1): the bundle boots in every
    /// mode, with the NORMALISED mode baked in so the in-page plan
    /// (pipeline-plan.mjs) can gate what actually runs. Unrecognised
    /// modes must land on "off", never leak through as-is.
    #[test]
    fn gaze_injects_in_every_mode_with_normalised_mode_string() {
        for (mode, baked) in [("off", "off"), ("blur", "blur"), ("smart", "smart"), ("", "off"), ("bogus", "off")] {
            let script = gaze_script(mode);
            assert!(
                script.contains(&format!("window.__TS_GAZE_MODE = \"{baked}\";")),
                "mode {mode:?} must bake __TS_GAZE_MODE {baked:?}"
            );
            assert!(script.contains("__TS_GAZE_BUNDLE__"), "mode {mode:?} must carry the bundle");
        }
    }

    /// gaze_mode() must fall back to "off" for anything it doesn't
    /// recognise, never silently pass an unknown string through to the
    /// webview-building code.
    #[test]
    fn unknown_gaze_mode_falls_back_to_off() {
        assert_eq!(gaze_mode("smart"), "smart");
        assert_eq!(gaze_mode("blur"), "blur");
        assert_eq!(gaze_mode("off"), "off");
        assert_eq!(gaze_mode("nonsense"), "off");
        assert_eq!(gaze_mode(""), "off");
    }
}


