//! tamescroll — a narrow shell that opens only the feeds, cleaned.
//!
//! The blocking engine is Brave's `adblock` crate. We do not implement
//! filtering ourselves; we hand it EasyList-syntax rules and ask it what
//! to hide for a given URL. See NOTICE.

use std::collections::HashMap;
use std::sync::OnceLock;

use adblock::cosmetic_filter_cache::ProceduralOrActionFilter;
use adblock::Engine;
use serde::Serialize;
use tauri::{Manager, WebviewUrl, WebviewWindowBuilder};

mod rules;

/// Stage A gaze blur (docs/plan.md Phase 4): plain CSS, opt-in, appended to
/// the injected stylesheet only when the launcher's blur toggle is on. Not
/// EasyList syntax and not run through the cosmetic-filter engine — these
/// files are `filter: blur(...)` rules on chosen media selectors, kept
/// separate from rules/*.txt because blurring is a personal choice and the
/// mechanism (plain CSS) differs from cosmetic hiding.
const BLUR_CSS: &[(&str, &str)] = &[
    ("youtube", include_str!("../../../rules/blur/youtube.css")),
    ("reddit", include_str!("../../../rules/blur/reddit.css")),
    ("x", include_str!("../../../rules/blur/x.css")),
];

fn blur_css(platform_id: &str) -> &'static str {
    BLUR_CSS
        .iter()
        .find(|(id, _)| *id == platform_id)
        .map(|(_, css)| *css)
        .unwrap_or("")
}

/// Stage B gaze bundle (docs/gaze-research.md): the built JS runtime that
/// base64-embeds BlazeFace and blurs-first via injected CSS, then
/// unblurs faceless media via on-device inference. Generated by
/// `npm run build:gaze` in app/gaze/ — a committed generated artifact,
/// same treatment as the vendored rule-list snapshots in rules/vendor/.
const GAZE_INIT_JS: &str = include_str!("../gaze-init.js");

/// Normalises the launcher's gaze mode: unknown values fall back to
/// "off" rather than risk an unrecognised mode silently doing nothing
/// while claiming to be active.
fn gaze_mode(mode: &str) -> &'static str {
    match mode {
        "smart" => "smart",
        "blur" => "blur",
        _ => "off",
    }
}

/// Script that boots gaze Stage B, or nothing outside "smart" mode.
/// Wrapped in its own try/catch on top of the bundle's internal
/// fail-open handling — a syntax-level break in the generated bundle
/// must not be able to take the rest of the injected script down with
/// it, matching the pattern already used for scriptlets below.
fn gaze_script(mode: &str) -> String {
    if gaze_mode(mode) != "smart" {
        return String::new();
    }
    format!(
        r#"
(function () {{
  try {{
    window.__TS_GAZE_MODE = "smart";
{GAZE_INIT_JS}
  }} catch (e) {{}}
}})();
"#
    )
}

/// Our own surfaces' CSS (docs/plan.md Phase 3 settings pane): one rule
/// per selector, same hard-won-lesson formatting as `cosmetic_css` below,
/// for every surface not in `shown` — always_on surfaces (ads) are never
/// skipped, no matter what `shown` contains, because ad-hiding is not
/// user-toggleable (VISION.md). `shown` entries that don't name a real
/// surface for this platform are simply never matched, i.e. ignored.
///
/// Every rule of the platform ships regardless of its `domain` column:
/// the injected CSS is built ONCE per window, but Android's UA redirect
/// moves that same window from www.youtube.com to m.youtube.com (seen on
/// the emulator 2026-08-18 — the Shorts tab survived precisely because
/// the m.youtube rules were host-filtered out at injection time).
/// Desktop and mobile selectors target disjoint element sets (ytd-* vs
/// ytm-*), so cross-shipping is harmless where filtering was actively
/// wrong.
fn surfaces_css(platform_id: &str, shown: &[String]) -> String {
    let Some(surfaces) = rules::platform_surfaces(platform_id) else {
        return String::new();
    };

    let mut css = String::new();
    for surface in surfaces {
        let is_shown = !surface.always_on && shown.iter().any(|id| id == surface.id);
        if is_shown {
            continue;
        }
        for (_domain, selector) in &surface.rules {
            css.push_str(selector);
            css.push_str(" { display: none !important; }\n");
        }
    }
    css
}

/// The full stylesheet injected into a platform window: cosmetic hiding
/// always, our own surfaces next (minus whatever the user chose to show),
/// Stage A blur appended last (same stylesheet, no separate style
/// element) only when the launcher toggle is on.
fn page_css(url: &str, platform_id: &str, blur: bool, shown: &[String]) -> String {
    let mut css = cosmetic_css(url);
    css.push_str(&surfaces_css(platform_id, shown));
    if blur {
        css.push_str(blur_css(platform_id));
    }
    css
}

/// Rules are compiled in for now. Phase 6 replaces this with a cached
/// fetch of the hosted list so fixes ship without an app update — the
/// engine stays put, only the data moves. Building it from the full
/// vendored list set (EasyList, EasyPrivacy, uBO filters, scriptlet
/// resources) takes on the order of a second, so `run()` warms it on a
/// background thread instead of paying that cost on the first tile click.
static ENGINE: OnceLock<Engine> = OnceLock::new();

fn engine() -> &'static Engine {
    ENGINE.get_or_init(rules::build_engine)
}

#[derive(Serialize, Clone)]
pub struct Platform {
    id: &'static str,
    name: &'static str,
    url: &'static str,
    /// Brand colour, used by the launcher tile.
    tint: &'static str,
    /// Whether this platform is coherent once cleaned. See docs/plan.md —
    /// TikTok is deliberately absent because removing the For You feed
    /// leaves nothing to open.
    ready: bool,
}

const PLATFORMS: &[Platform] = &[
    Platform {
        id: "youtube",
        name: "YouTube",
        url: "https://www.youtube.com/",
        tint: "#FF0033",
        ready: true,
    },
    Platform {
        id: "reddit",
        name: "Reddit",
        url: "https://www.reddit.com/",
        tint: "#FF4500",
        ready: true,
    },
    Platform {
        id: "x",
        name: "X",
        // /home lands on the timeline; our rules remove the For-you tab
        // there, leaving Following as the only one.
        url: "https://x.com/home",
        tint: "#71767B",
        ready: true,
    },
    Platform {
        id: "instagram",
        name: "Instagram",
        url: "https://www.instagram.com/",
        tint: "#E1306C",
        ready: false,
    },
];

#[tauri::command]
fn platforms() -> Vec<Platform> {
    PLATFORMS.to_vec()
}

/// Build the CSS the engine says applies to this URL.
fn cosmetic_css(url: &str) -> String {
    let res = engine().url_cosmetic_resources(url);

    let mut css = String::new();

    if !res.hide_selectors.is_empty() {
        let mut selectors: Vec<&String> = res.hide_selectors.iter().collect();
        // Deterministic output keeps the injected script stable between
        // runs, which makes debugging a broken rule far easier.
        selectors.sort();
        // ONE RULE PER SELECTOR — never join them. In a comma-separated
        // selector list, a single invalid selector invalidates the whole
        // rule, and with thousands of upstream EasyList selectors in play
        // one bad apple silently turned off ALL hiding (Shorts came back;
        // caught by screenshot 2026-08-18). Per-selector rules contain
        // the damage to the one selector that is broken.
        for selector in selectors {
            css.push_str(selector);
            css.push_str(" { display: none !important; }\n");
        }
    }

    // `:style()` rules and other actioned filters arrive JSON-encoded.
    // Those expressible as plain CSS become rules here; the rest need a
    // JS-side evaluator we do not have yet, so they are skipped rather
    // than half-applied. Skipping a blur is survivable; a broken
    // selector that hides the player is not.
    let mut styled: Vec<(String, String)> = res
        .procedural_actions
        .iter()
        .filter_map(|encoded| serde_json::from_str::<ProceduralOrActionFilter>(encoded).ok())
        .filter_map(|filter| filter.as_css())
        .collect();
    styled.sort();
    for (selector, declarations) in styled {
        css.push_str(&format!("{selector} {{ {declarations} }}\n"));
    }

    css
}

/// Surface info the settings pane renders from, not a hardcoded copy of
/// `rules/*.txt`'s ids and labels. Always-on surfaces (ads) are excluded —
/// there is nothing to toggle, per VISION.md.
#[derive(Serialize, Clone)]
pub struct SurfaceInfo {
    id: String,
    label: String,
}

#[tauri::command]
fn surfaces(id: String) -> Vec<SurfaceInfo> {
    rules::platform_surfaces(&id)
        .map(|surfaces| {
            surfaces
                .iter()
                .filter(|s| !s.always_on)
                .map(|s| SurfaceInfo {
                    id: s.id.to_string(),
                    label: s.label.to_string(),
                })
                .collect()
        })
        .unwrap_or_default()
}

/// "N rules active" for the launcher status line: the engine's own
/// vendor-list hide selectors plus our own surface rules (default state —
/// nothing shown — matches the fully-cleaned experience every install
/// starts with).
#[tauri::command]
fn rules_summary() -> HashMap<String, usize> {
    let mut out = HashMap::new();
    for p in PLATFORMS {
        let engine_count = engine().url_cosmetic_resources(p.url).hide_selectors.len();
        let surface_count = rules::platform_surfaces(p.id)
            .map(|surfaces| surfaces.iter().map(|s| s.rules.len()).sum())
            .unwrap_or(0);
        out.insert(p.id.to_string(), engine_count + surface_count);
    }
    out
}

/// The script injected into every platform webview.
///
/// `scriptlets` is the engine's `injected_script` for this URL — the
/// scriptlets that strip ad data out of the page before its own scripts
/// read it (YouTube's player response, mainly; see VISION.md). It runs
/// first, and is wrapped in its own `try`/`catch` on top of the one each
/// individual scriptlet already gets from adblock-rust: a vendored
/// scriptlet that fails to parse must not be able to take the CSS
/// injection down with it.
///
/// The CSS block re-applies on SPA navigation because these sites rewrite
/// their own DOM without a page load, and Tauri's initialisation script is
/// not guaranteed to run before the site's own JavaScript on remote URLs.
/// Re-applying is cheap; missing a navigation is not.
fn injection_script(css: &str, scriptlets: &str) -> String {
    let escaped = css.replace('\\', "\\\\").replace('`', "\\`");
    format!(
        r#"
(function () {{
  try {{
{scriptlets}
  }} catch (e) {{}}
}})();

(function () {{
  var CSS = `{escaped}`;
  var STYLE_ID = "tamescroll-rules";

  function apply() {{
    if (document.getElementById(STYLE_ID)) return;
    var head = document.head || document.documentElement;
    if (!head) return;
    var el = document.createElement("style");
    el.id = STYLE_ID;
    el.textContent = CSS;
    head.appendChild(el);
  }}

  apply();
  document.addEventListener("DOMContentLoaded", apply);

  // These sites navigate without a page load. Re-assert after each one.
  ["pushState", "replaceState"].forEach(function (name) {{
    var original = history[name];
    history[name] = function () {{
      var result = original.apply(this, arguments);
      setTimeout(apply, 0);
      return result;
    }};
  }});
  window.addEventListener("popstate", function () {{ setTimeout(apply, 0); }});

  // Last resort: if the site tears our style out, put it back.
  new MutationObserver(function () {{ apply(); }})
    .observe(document.documentElement, {{ childList: true, subtree: false }});
}})();
"#
    )
}

/// Root domain a platform's rules key on: the platform URL's host minus
/// a leading `www.` — `youtube.com`, `reddit.com`, `x.com`.
#[cfg_attr(not(target_os = "android"), allow(dead_code))]
fn platform_root(url: &str) -> &str {
    let host = url
        .split("://")
        .nth(1)
        .unwrap_or(url)
        .split('/')
        .next()
        .unwrap_or(url);
    host.strip_prefix("www.").unwrap_or(host)
}

/// Android-only injection (docs/android-research.md, emulator findings
/// 2026-08-18): tapping a tile there does NOT create a new window — it
/// navigates the launcher's own single WebView, so a per-window
/// `initialization_script` never reaches the platform page at all (this
/// is how the Shorts tab survived two builds). A Tauri *plugin* script
/// applies to every webview and re-runs on every page load, so this one
/// dispatches on `location.host` at runtime: our surface rules for the
/// matching platform, defaults only (everything hidden, no blur, no
/// gaze — Android settings/mode plumbing is a follow-up, as are the
/// vendor cosmetic lists and scriptlets, which need the warmed engine
/// and can't block app startup).
#[cfg_attr(not(target_os = "android"), allow(dead_code))]
fn universal_injection_script() -> String {
    let mut branches = String::new();
    for p in PLATFORMS {
        if rules::platform_surfaces(p.id).is_none() {
            continue;
        }
        let css = surfaces_css(p.id, &[]);
        let escaped = css.replace('\\', "\\\\").replace('`', "\\`");
        let root = platform_root(p.url);
        branches.push_str(&format!(
            "    if (h === \"{root}\" || h.endsWith(\".{root}\")) return `{escaped}`;\n"
        ));
    }

    // Debug builds carry boundary markers so `adb logcat` (Tauri/Console)
    // shows exactly how far the injection pipeline got on-device:
    // enter -> host -> matched/no-match -> applied. Compiled out of
    // release builds.
    let trace = if cfg!(debug_assertions) {
        r#"var TS_LOG = function (m) { try { console.log("TS_UNIVERSAL " + m); } catch (e) {} };"#
    } else {
        r#"var TS_LOG = function () {};"#
    };

    format!(
        r#"
(function () {{
  {trace}
  if (window.__TS_UNIVERSAL__) {{ TS_LOG("skip: already ran"); return; }}
  window.__TS_UNIVERSAL__ = 1;

  var h = location.host;
  TS_LOG("enter host=" + h);
  var CSS = (function () {{
{branches}    return "";
  }})();
  if (!CSS) {{ TS_LOG("no-match host=" + h); return; }}
  TS_LOG("matched host=" + h + " css_len=" + CSS.length);

  var STYLE_ID = "tamescroll-rules";

  function apply() {{
    if (document.getElementById(STYLE_ID)) return;
    var head = document.head || document.documentElement;
    if (!head) return;
    var el = document.createElement("style");
    el.id = STYLE_ID;
    el.textContent = CSS;
    head.appendChild(el);
  }}

  apply();
  document.addEventListener("DOMContentLoaded", apply);

  ["pushState", "replaceState"].forEach(function (name) {{
    var original = history[name];
    history[name] = function () {{
      var result = original.apply(this, arguments);
      setTimeout(apply, 0);
      return result;
    }};
  }});
  window.addEventListener("popstate", function () {{ setTimeout(apply, 0); }});

  new MutationObserver(function () {{ apply(); }})
    .observe(document.documentElement, {{ childList: true, subtree: false }});

  setTimeout(function () {{
    TS_LOG(
      "t+5s style_present=" + !!document.getElementById(STYLE_ID) +
      " readyState=" + document.readyState
    );
  }}, 5000);
}})();
"#
    )
}

/// The plugin carrying `universal_injection_script` into every webview.
/// Android-only: on desktop each platform window gets its own richer
/// script (vendor cosmetics, scriptlets, mode and shown prefs) and this
/// would only double up.
#[cfg(target_os = "android")]
fn injection_plugin<R: tauri::Runtime>() -> tauri::plugin::TauriPlugin<R> {
    tauri::plugin::Builder::new("ts-inject")
        .js_init_script(universal_injection_script())
        .build()
}

// Android: everything after the navigate-and-return block is
// desktop-only builder code the compiler sees as unreachable there.
#[cfg_attr(target_os = "android", allow(unreachable_code, unused_variables))]
#[tauri::command]
async fn open_platform(
    app: tauri::AppHandle,
    id: String,
    mode: String,
    shown: Vec<String>,
) -> Result<(), String> {
    let platform = PLATFORMS
        .iter()
        .find(|p| p.id == id)
        .ok_or_else(|| format!("unknown platform: {id}"))?;

    #[cfg(debug_assertions)]
    eprintln!("open_platform id={id}");

    let url: tauri::Url = platform
        .url
        .parse()
        .map_err(|_| format!("bad platform url: {}", platform.url))?;

    // Android is a single-webview platform: never create or focus a
    // second window. The old label-reuse guard called set_focus() and
    // returned Ok — visually a no-op, so every tile tap after the first
    // "succeeded" silently (probe evidence 2026-08-18, spikes/
    // logcat-probe7.log: JS "open ok" with no visible effect). Navigate
    // the main webview in place instead; cosmetic injection rides the
    // ts-inject plugin script, which fires on every page load.
    #[cfg(target_os = "android")]
    {
        let main = app
            .get_webview_window("main")
            .ok_or_else(|| "no main webview".to_string())?;
        let nav = main.navigate(url);
        #[cfg(debug_assertions)]
        eprintln!("open_platform navigate main -> {nav:?}");
        return nav.map_err(|e| e.to_string());
    }

    // Desktop: re-opening a platform whose window is still open just
    // focuses it — a second Builder::build on a taken label would error.
    #[cfg(not(target_os = "android"))]
    if let Some(existing) = app.get_webview_window(platform.id) {
        existing.set_focus().map_err(|e| e.to_string())?;
        return Ok(());
    }

    let mode = gaze_mode(&mode);
    let resources = engine().url_cosmetic_resources(platform.url);
    let mut script = injection_script(
        &page_css(platform.url, platform.id, mode == "blur", &shown),
        &resources.injected_script,
    );
    script.push_str(&gaze_script(mode));

    let built = WebviewWindowBuilder::new(&app, platform.id, WebviewUrl::External(url))
        .title(platform.name)
        .inner_size(1200.0, 860.0)
        .initialization_script(&script)
        .build();
    #[cfg(debug_assertions)]
    eprintln!(
        "open_platform build id={} -> {:?}",
        platform.id,
        built.as_ref().map(|_| ()).map_err(|e| e.to_string())
    );
    built.map_err(|e| e.to_string())?;

    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Warm the engine off the critical path: building it from the full
    // vendored list set takes on the order of a second, and nothing about
    // startup needs it until the first `open_platform` call.
    std::thread::spawn(|| {
        #[cfg(debug_assertions)]
        let started = std::time::Instant::now();
        engine();
        #[cfg(debug_assertions)]
        eprintln!("adblock engine warmed in {:?}", started.elapsed());
    });

    let builder = tauri::Builder::default().plugin(tauri_plugin_opener::init());

    // Android: the single-WebView model means per-window injection never
    // fires — the plugin script is the only reliable delivery there.
    #[cfg(target_os = "android")]
    let builder = builder.plugin(injection_plugin());

    builder
        .invoke_handler(tauri::generate_handler![
            platforms,
            open_platform,
            rules_summary,
            surfaces
        ])
        .run(tauri::generate_context!())
        .expect("error while running tamescroll");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Proves the two halves of in-app ad blocking VISION.md describes are
    /// actually wired: cosmetic hiding (already worked) and scriptlet
    /// injection (the point of this change). A regression here means
    /// either the vendored lists didn't load or the scriptlet resources
    /// didn't — see rules.rs and rules/vendor/README.md.
    #[test]
    fn youtube_gets_hide_selectors_and_a_scriptlet_injection() {
        let resources =
            engine().url_cosmetic_resources("https://www.youtube.com/watch?v=aqz-KE-bpKQ");
        assert!(
            !resources.injected_script.is_empty(),
            "expected a non-empty scriptlet injection for a YouTube watch page — \
             this is what strips ad data out of the player response"
        );
        // Our clean-room scriptlets, resolved by name from the filter
        // lists: the initial-load pin and the SPA-navigation strippers.
        for needle in [
            "setConstant(",
            "trustedReplaceFetchResponse(",
            "trustedReplaceXhrResponse(",
        ] {
            assert!(
                resources.injected_script.contains(needle),
                "expected {needle:?} in the YouTube injection — a scriptlet \
                 name stopped resolving (see rules.rs SCRIPTLETS)"
            );
        }

        // Home-page hide selectors used to come only from youtube.txt's
        // own rules inside the engine; Phase 3 moved those out into our
        // own surfaces (see rules.rs), so this now goes through the same
        // page_css() path the app actually injects — the assertion (some
        // hide selectors reach a YouTube home page) is unchanged.
        let css = page_css("https://www.youtube.com/", "youtube", false, &[]);
        assert!(
            css.contains("display: none !important;"),
            "expected cosmetic hide selectors for the YouTube home page"
        );
    }

    /// Our own platform rules must survive the trip through the parser
    /// and into the assembled page CSS — a selector that fails to parse
    /// is silently dropped, and this is where that would surface. Moved
    /// off the raw engine call in Phase 3 (docs/plan.md settings pane):
    /// these rules no longer live in the engine's FilterSet, they live in
    /// rules.rs's surface parser and get assembled by page_css().
    #[test]
    fn reddit_and_x_rules_survive_parsing() {
        let reddit_css = page_css("https://www.reddit.com/", "reddit", false, &[]);
        assert!(
            reddit_css.contains("shreddit-ad-post"),
            "reddit.txt's ad rules should be present for reddit.com"
        );

        let x_css = page_css("https://x.com/home", "x", false, &[]);
        assert!(
            !x_css.is_empty(),
            "x.txt rules should produce CSS for x.com"
        );
    }

    /// The launcher toggle must actually change what gets injected —
    /// this is the wire between the UI and the page.
    #[test]
    fn blur_toggle_reaches_the_injected_stylesheet() {
        let off = page_css("https://www.youtube.com/", "youtube", false, &[]);
        let on = page_css("https://www.youtube.com/", "youtube", true, &[]);
        assert!(!off.contains("blur("), "blur css must be absent when off");
        assert!(on.contains("blur("), "blur css must be present when on");
    }

    /// Bring-back settings (docs/plan.md Phase 3): showing one surface
    /// must remove only that surface's selectors from the injected CSS —
    /// other surfaces (here: home) must be untouched.
    #[test]
    fn showing_one_surface_hides_only_that_surface() {
        let default_css = page_css("https://www.youtube.com/", "youtube", false, &[]);
        assert!(
            default_css.contains("ytd-reel-shelf-renderer"),
            "shorts selectors should be present by default"
        );
        assert!(
            default_css.contains("ytd-rich-grid-renderer"),
            "home selectors should be present by default"
        );

        let shorts_shown = page_css(
            "https://www.youtube.com/",
            "youtube",
            false,
            &["shorts".to_string()],
        );
        assert!(
            !shorts_shown.contains("ytd-reel-shelf-renderer"),
            "shorts selectors must be absent once shorts is shown"
        );
        assert!(
            shorts_shown.contains("ytd-rich-grid-renderer"),
            "home selectors must remain when only shorts is shown"
        );
    }

    /// VISION.md: ad-hiding is never user-toggleable. Even if the
    /// frontend somehow sent "ads" in `shown` (it never offers the
    /// option — see the `surfaces` command), the always_on surface must
    /// stay hidden.
    #[test]
    fn always_on_ads_surface_cannot_be_shown() {
        let css = page_css(
            "https://www.youtube.com/",
            "youtube",
            false,
            &["ads".to_string()],
        );
        assert!(
            css.contains("ytd-ad-slot-renderer"),
            "the always-on ads surface must stay hidden even when 'shown' asks for it"
        );
    }

    /// Stage A blur CSS (docs/plan.md Phase 4) must actually blur something
    /// on every platform, and must never list the watch-page player as a
    /// target — that is the one surface the module exists to leave alone.
    #[test]
    fn blur_css_is_present_and_never_targets_the_player() {
        for (id, css) in BLUR_CSS {
            assert!(!css.is_empty(), "blur css for {id} must not be empty");
            assert!(
                css.contains("blur("),
                "blur css for {id} should contain a blur() filter"
            );
        }

        assert!(
            !blur_css("youtube").contains("#movie_player video"),
            "the YouTube blur css must never target #movie_player video — \
             the video the user is watching must never blur"
        );
    }

    /// Owner report 2026-08-18: search results were still full of
    /// "People also search for" / "Channels new to you" wedges. The
    /// fix lives in rules/youtube.txt — this pins those selectors all
    /// the way through to the CSS a search page receives. Goes through
    /// page_css() rather than the bare engine call since Phase 3 moved
    /// these selectors out of the engine and into our own surface rules
    /// (rules.rs) — same assertions, different plumbing.
    #[test]
    fn youtube_search_inserts_are_hidden_in_the_injected_css() {
        let css = page_css(
            "https://www.youtube.com/results?search_query=minecraft",
            "youtube",
            false,
            &[],
        );
        for sel in [
            "ytd-search-pyv-renderer",
            "ytd-search ytd-shelf-renderer",
            "ytd-search ytd-horizontal-card-list-renderer",
            "ytd-universal-watch-card-renderer",
        ] {
            assert!(
                css.contains(sel),
                "expected search-insert selector {sel:?} in the injected CSS"
            );
        }
    }

    /// The Android delivery path (single WebView, plugin script) must
    /// carry every platform's rules and dispatch on host — including the
    /// m.youtube.com rules that the emulator proved are the ones Android
    /// actually needs.
    #[test]
    fn universal_script_carries_all_platforms_and_dispatches_on_host() {
        let script = universal_injection_script();
        for marker in [
            "\"youtube.com\"",
            "\"reddit.com\"",
            "\"x.com\"",
            "ytm-pivot-bar-item-renderer",
            "ytd-browse[page-subtype=\\\"home\\\"]",
            "shreddit-app",
            "__TS_UNIVERSAL__",
        ] {
            let found = script.contains(marker)
                || script.contains(&marker.replace("\\\"", "\""));
            assert!(found, "expected {marker:?} in the universal script");
        }
    }

    /// Emulator lesson 2026-08-18: Android's UA redirect moves the
    /// YouTube window to m.youtube.com AFTER injection, so the mobile
    /// (ytm-*) rules must ship in the window's CSS even though the
    /// platform URL says www.youtube.com — host-filtering them out is
    /// how the Shorts tab survived on the first Android run.
    #[test]
    fn mobile_youtube_rules_ship_in_the_desktop_window_css() {
        let css = page_css("https://www.youtube.com/", "youtube", false, &[]);
        assert!(
            css.contains("ytm-pivot-bar-item-renderer"),
            "m.youtube.com Shorts-tab rule must be in the injected CSS"
        );
        assert!(
            css.contains("ytm-reel-shelf-renderer"),
            "m.youtube.com Shorts-shelf rule must be in the injected CSS"
        );
    }

    /// Stage B (gaze-research.md): the generated runtime must actually be
    /// present in the binary and non-trivial — an empty or missing bundle
    /// would mean "smart" silently degrades to doing nothing.
    #[test]
    fn gaze_bundle_is_non_empty() {
        assert!(
            !GAZE_INIT_JS.is_empty(),
            "app/src-tauri/gaze-init.js is empty or missing — run `npm run build:gaze` in app/"
        );
    }

    /// The launcher's mode picker must actually change what gets
    /// injected — this is the wire between the "Smart" option and the
    /// page, same role as blur_toggle_reaches_the_injected_stylesheet
    /// plays for Stage A.
    #[test]
    fn smart_mode_injects_the_gaze_bundle_with_its_marker() {
        let script = gaze_script("smart");
        assert!(
            !script.is_empty(),
            "smart mode must inject a non-empty gaze script"
        );
        assert!(
            script.contains("__TS_GAZE_BUNDLE__"),
            "expected the gaze bundle's minification-proof marker in the \
             smart-mode injection — see gaze/src/init-entry.js"
        );
        assert!(
            script.contains("window.__TS_GAZE_MODE = \"smart\";"),
            "smart mode must set window.__TS_GAZE_MODE before the bundle runs"
        );
    }

    /// "off" (and any unrecognised mode) must never inject the gaze
    /// bundle — a stray gaze script running while the user picked "off"
    /// would mean spending CPU/battery on inference nobody asked for.
    #[test]
    fn gaze_never_injects_outside_smart_mode() {
        for mode in ["off", "blur", "", "bogus"] {
            let script = gaze_script(mode);
            assert!(
                script.is_empty(),
                "mode {mode:?} must not inject the gaze bundle, got {} bytes",
                script.len()
            );
        }
    }

    /// gaze_mode() must fall back to "off" for anything it doesn't
    /// recognise, never silently pass an unknown string through to the
    /// webview-building code.
    #[test]
    fn unknown_gaze_mode_falls_back_to_off() {
        assert_eq!(gaze_mode("smart"), "smart");
        assert_eq!(gaze_mode("blur"), "blur");
        assert_eq!(gaze_mode("off"), "off");
        assert_eq!(gaze_mode("nonsense"), "off");
        assert_eq!(gaze_mode(""), "off");
    }
}
