//! tamescroll — a narrow shell that opens only the feeds, cleaned.
//!
//! The blocking engine is Brave's `adblock` crate. We do not implement
//! filtering ourselves; we hand it EasyList-syntax rules and ask it what
//! to hide for a given URL. See NOTICE.

use std::collections::HashMap;
use std::sync::OnceLock;

use adblock::cosmetic_filter_cache::ProceduralOrActionFilter;
use adblock::Engine;
use serde::Serialize;
use tauri::{Manager, WebviewUrl, WebviewWindowBuilder};

mod rules;

/// Stage A gaze blur (docs/plan.md Phase 4): plain CSS, opt-in, appended to
/// the injected stylesheet only when the launcher's blur toggle is on. Not
/// EasyList syntax and not run through the cosmetic-filter engine — these
/// files are `filter: blur(...)` rules on chosen media selectors, kept
/// separate from rules/*.txt because blurring is a personal choice and the
/// mechanism (plain CSS) differs from cosmetic hiding.
const BLUR_CSS: &[(&str, &str)] = &[
    ("youtube", include_str!("../../../rules/blur/youtube.css")),
    ("reddit", include_str!("../../../rules/blur/reddit.css")),
    ("x", include_str!("../../../rules/blur/x.css")),
];

fn blur_css(platform_id: &str) -> &'static str {
    BLUR_CSS
        .iter()
        .find(|(id, _)| *id == platform_id)
        .map(|(_, css)| *css)
        .unwrap_or("")
}

/// Stage B gaze bundle (docs/gaze-research.md): the built JS runtime that
/// base64-embeds BlazeFace and blurs-first via injected CSS, then
/// unblurs faceless media via on-device inference. Generated by
/// `npm run build:gaze` in app/gaze/ — a committed generated artifact,
/// same treatment as the vendored rule-list snapshots in rules/vendor/.
const GAZE_INIT_JS: &str = include_str!("../gaze-init.js");

/// Normalises the launcher's gaze mode: unknown values fall back to
/// "off" rather than risk an unrecognised mode silently doing nothing
/// while claiming to be active.
fn gaze_mode(mode: &str) -> &'static str {
    match mode {
        "smart" => "smart",
        "blur" => "blur",
        _ => "off",
    }
}

/// Script that boots gaze Stage B, or nothing outside "smart" mode.
/// Wrapped in its own try/catch on top of the bundle's internal
/// fail-open handling — a syntax-level break in the generated bundle
/// must not be able to take the rest of the injected script down with
/// it, matching the pattern already used for scriptlets below.
fn gaze_script(mode: &str) -> String {
    if gaze_mode(mode) != "smart" {
        return String::new();
    }
    format!(
        r#"
(function () {{
  try {{
    window.__TS_GAZE_MODE = "smart";
{GAZE_INIT_JS}
  }} catch (e) {{}}
}})();
"#
    )
}

/// The full stylesheet injected into a platform window: cosmetic hiding
/// always, Stage A blur appended (same stylesheet, no separate style
/// element) only when the launcher toggle is on.
fn page_css(url: &str, platform_id: &str, blur: bool) -> String {
    let mut css = cosmetic_css(url);
    if blur {
        css.push_str(blur_css(platform_id));
    }
    css
}

/// Rules are compiled in for now. Phase 6 replaces this with a cached
/// fetch of the hosted list so fixes ship without an app update — the
/// engine stays put, only the data moves. Building it from the full
/// vendored list set (EasyList, EasyPrivacy, uBO filters, scriptlet
/// resources) takes on the order of a second, so `run()` warms it on a
/// background thread instead of paying that cost on the first tile click.
static ENGINE: OnceLock<Engine> = OnceLock::new();

fn engine() -> &'static Engine {
    ENGINE.get_or_init(rules::build_engine)
}

#[derive(Serialize, Clone)]
pub struct Platform {
    id: &'static str,
    name: &'static str,
    url: &'static str,
    /// Brand colour, used by the launcher tile.
    tint: &'static str,
    /// Whether this platform is coherent once cleaned. See docs/plan.md —
    /// TikTok is deliberately absent because removing the For You feed
    /// leaves nothing to open.
    ready: bool,
}

const PLATFORMS: &[Platform] = &[
    Platform {
        id: "youtube",
        name: "YouTube",
        url: "https://www.youtube.com/",
        tint: "#FF0033",
        ready: true,
    },
    Platform {
        id: "reddit",
        name: "Reddit",
        url: "https://www.reddit.com/",
        tint: "#FF4500",
        ready: true,
    },
    Platform {
        id: "x",
        name: "X",
        // /home lands on the timeline; our rules remove the For-you tab
        // there, leaving Following as the only one.
        url: "https://x.com/home",
        tint: "#71767B",
        ready: true,
    },
    Platform {
        id: "instagram",
        name: "Instagram",
        url: "https://www.instagram.com/",
        tint: "#E1306C",
        ready: false,
    },
];

#[tauri::command]
fn platforms() -> Vec<Platform> {
    PLATFORMS.to_vec()
}

/// Build the CSS the engine says applies to this URL.
fn cosmetic_css(url: &str) -> String {
    let res = engine().url_cosmetic_resources(url);

    let mut css = String::new();

    if !res.hide_selectors.is_empty() {
        let mut selectors: Vec<&String> = res.hide_selectors.iter().collect();
        // Deterministic output keeps the injected script stable between
        // runs, which makes debugging a broken rule far easier.
        selectors.sort();
        // ONE RULE PER SELECTOR — never join them. In a comma-separated
        // selector list, a single invalid selector invalidates the whole
        // rule, and with thousands of upstream EasyList selectors in play
        // one bad apple silently turned off ALL hiding (Shorts came back;
        // caught by screenshot 2026-08-18). Per-selector rules contain
        // the damage to the one selector that is broken.
        for selector in selectors {
            css.push_str(selector);
            css.push_str(" { display: none !important; }\n");
        }
    }

    // `:style()` rules and other actioned filters arrive JSON-encoded.
    // Those expressible as plain CSS become rules here; the rest need a
    // JS-side evaluator we do not have yet, so they are skipped rather
    // than half-applied. Skipping a blur is survivable; a broken
    // selector that hides the player is not.
    let mut styled: Vec<(String, String)> = res
        .procedural_actions
        .iter()
        .filter_map(|encoded| serde_json::from_str::<ProceduralOrActionFilter>(encoded).ok())
        .filter_map(|filter| filter.as_css())
        .collect();
    styled.sort();
    for (selector, declarations) in styled {
        css.push_str(&format!("{selector} {{ {declarations} }}\n"));
    }

    css
}

#[tauri::command]
fn rules_summary() -> HashMap<String, usize> {
    let mut out = HashMap::new();
    for p in PLATFORMS {
        let count = engine().url_cosmetic_resources(p.url).hide_selectors.len();
        out.insert(p.id.to_string(), count);
    }
    out
}

/// The script injected into every platform webview.
///
/// `scriptlets` is the engine's `injected_script` for this URL — the
/// scriptlets that strip ad data out of the page before its own scripts
/// read it (YouTube's player response, mainly; see VISION.md). It runs
/// first, and is wrapped in its own `try`/`catch` on top of the one each
/// individual scriptlet already gets from adblock-rust: a vendored
/// scriptlet that fails to parse must not be able to take the CSS
/// injection down with it.
///
/// The CSS block re-applies on SPA navigation because these sites rewrite
/// their own DOM without a page load, and Tauri's initialisation script is
/// not guaranteed to run before the site's own JavaScript on remote URLs.
/// Re-applying is cheap; missing a navigation is not.
fn injection_script(css: &str, scriptlets: &str) -> String {
    let escaped = css.replace('\\', "\\\\").replace('`', "\\`");
    format!(
        r#"
(function () {{
  try {{
{scriptlets}
  }} catch (e) {{}}
}})();

(function () {{
  var CSS = `{escaped}`;
  var STYLE_ID = "tamescroll-rules";

  function apply() {{
    if (document.getElementById(STYLE_ID)) return;
    var head = document.head || document.documentElement;
    if (!head) return;
    var el = document.createElement("style");
    el.id = STYLE_ID;
    el.textContent = CSS;
    head.appendChild(el);
  }}

  apply();
  document.addEventListener("DOMContentLoaded", apply);

  // These sites navigate without a page load. Re-assert after each one.
  ["pushState", "replaceState"].forEach(function (name) {{
    var original = history[name];
    history[name] = function () {{
      var result = original.apply(this, arguments);
      setTimeout(apply, 0);
      return result;
    }};
  }});
  window.addEventListener("popstate", function () {{ setTimeout(apply, 0); }});

  // Last resort: if the site tears our style out, put it back.
  new MutationObserver(function () {{ apply(); }})
    .observe(document.documentElement, {{ childList: true, subtree: false }});
}})();
"#
    )
}

#[tauri::command]
async fn open_platform(app: tauri::AppHandle, id: String, mode: String) -> Result<(), String> {
    let platform = PLATFORMS
        .iter()
        .find(|p| p.id == id)
        .ok_or_else(|| format!("unknown platform: {id}"))?;

    if let Some(existing) = app.get_webview_window(platform.id) {
        existing.set_focus().map_err(|e| e.to_string())?;
        return Ok(());
    }

    let url = platform
        .url
        .parse()
        .map_err(|_| format!("bad platform url: {}", platform.url))?;

    let mode = gaze_mode(&mode);
    let resources = engine().url_cosmetic_resources(platform.url);
    let mut script = injection_script(
        &page_css(platform.url, platform.id, mode == "blur"),
        &resources.injected_script,
    );
    script.push_str(&gaze_script(mode));

    WebviewWindowBuilder::new(&app, platform.id, WebviewUrl::External(url))
        .title(platform.name)
        .inner_size(1200.0, 860.0)
        .initialization_script(&script)
        .build()
        .map_err(|e| e.to_string())?;

    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Warm the engine off the critical path: building it from the full
    // vendored list set takes on the order of a second, and nothing about
    // startup needs it until the first `open_platform` call.
    std::thread::spawn(|| {
        #[cfg(debug_assertions)]
        let started = std::time::Instant::now();
        engine();
        #[cfg(debug_assertions)]
        eprintln!("adblock engine warmed in {:?}", started.elapsed());
    });

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            platforms,
            open_platform,
            rules_summary
        ])
        .run(tauri::generate_context!())
        .expect("error while running tamescroll");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Proves the two halves of in-app ad blocking VISION.md describes are
    /// actually wired: cosmetic hiding (already worked) and scriptlet
    /// injection (the point of this change). A regression here means
    /// either the vendored lists didn't load or the scriptlet resources
    /// didn't — see rules.rs and rules/vendor/README.md.
    #[test]
    fn youtube_gets_hide_selectors_and_a_scriptlet_injection() {
        let resources =
            engine().url_cosmetic_resources("https://www.youtube.com/watch?v=aqz-KE-bpKQ");
        assert!(
            !resources.injected_script.is_empty(),
            "expected a non-empty scriptlet injection for a YouTube watch page — \
             this is what strips ad data out of the player response"
        );
        // Our clean-room scriptlets, resolved by name from the filter
        // lists: the initial-load pin and the SPA-navigation strippers.
        for needle in [
            "setConstant(",
            "trustedReplaceFetchResponse(",
            "trustedReplaceXhrResponse(",
        ] {
            assert!(
                resources.injected_script.contains(needle),
                "expected {needle:?} in the YouTube injection — a scriptlet \
                 name stopped resolving (see rules.rs SCRIPTLETS)"
            );
        }

        let resources = engine().url_cosmetic_resources("https://www.youtube.com/");
        assert!(
            !resources.hide_selectors.is_empty(),
            "expected cosmetic hide selectors for the YouTube home page"
        );
    }

    /// Our own platform rules must survive the trip through the engine —
    /// a selector that fails to parse is silently dropped, and this is
    /// where that would surface.
    #[test]
    fn reddit_and_x_rules_survive_parsing() {
        let reddit = engine().url_cosmetic_resources("https://www.reddit.com/");
        assert!(
            reddit.hide_selectors.iter().any(|s| s.contains("shreddit-ad-post")),
            "reddit.txt's ad rules should be present for reddit.com"
        );

        let x = engine().url_cosmetic_resources("https://x.com/home");
        assert!(
            !x.hide_selectors.is_empty() || !x.procedural_actions.is_empty(),
            "x.txt rules should produce hide selectors or procedural actions for x.com"
        );
    }

    /// The launcher toggle must actually change what gets injected —
    /// this is the wire between the UI and the page.
    #[test]
    fn blur_toggle_reaches_the_injected_stylesheet() {
        let off = page_css("https://www.youtube.com/", "youtube", false);
        let on = page_css("https://www.youtube.com/", "youtube", true);
        assert!(!off.contains("blur("), "blur css must be absent when off");
        assert!(on.contains("blur("), "blur css must be present when on");
    }

    /// Stage A blur CSS (docs/plan.md Phase 4) must actually blur something
    /// on every platform, and must never list the watch-page player as a
    /// target — that is the one surface the module exists to leave alone.
    #[test]
    fn blur_css_is_present_and_never_targets_the_player() {
        for (id, css) in BLUR_CSS {
            assert!(!css.is_empty(), "blur css for {id} must not be empty");
            assert!(
                css.contains("blur("),
                "blur css for {id} should contain a blur() filter"
            );
        }

        assert!(
            !blur_css("youtube").contains("#movie_player video"),
            "the YouTube blur css must never target #movie_player video — \
             the video the user is watching must never blur"
        );
    }

    /// Owner report 2026-08-18: search results were still full of
    /// "People also search for" / "Channels new to you" wedges. The
    /// fix lives in rules/youtube.txt — this pins those selectors all
    /// the way through the engine into the CSS a search page receives.
    #[test]
    fn youtube_search_inserts_are_hidden_in_the_injected_css() {
        let css = cosmetic_css("https://www.youtube.com/results?search_query=minecraft");
        for sel in [
            "ytd-search-pyv-renderer",
            "ytd-search ytd-shelf-renderer",
            "ytd-search ytd-horizontal-card-list-renderer",
            "ytd-universal-watch-card-renderer",
        ] {
            assert!(
                css.contains(sel),
                "expected search-insert selector {sel:?} in the injected CSS"
            );
        }
    }

    /// Stage B (gaze-research.md): the generated runtime must actually be
    /// present in the binary and non-trivial — an empty or missing bundle
    /// would mean "smart" silently degrades to doing nothing.
    #[test]
    fn gaze_bundle_is_non_empty() {
        assert!(
            !GAZE_INIT_JS.is_empty(),
            "app/src-tauri/gaze-init.js is empty or missing — run `npm run build:gaze` in app/"
        );
    }

    /// The launcher's mode picker must actually change what gets
    /// injected — this is the wire between the "Smart" option and the
    /// page, same role as blur_toggle_reaches_the_injected_stylesheet
    /// plays for Stage A.
    #[test]
    fn smart_mode_injects_the_gaze_bundle_with_its_marker() {
        let script = gaze_script("smart");
        assert!(
            !script.is_empty(),
            "smart mode must inject a non-empty gaze script"
        );
        assert!(
            script.contains("__TS_GAZE_BUNDLE__"),
            "expected the gaze bundle's minification-proof marker in the \
             smart-mode injection — see gaze/src/init-entry.js"
        );
        assert!(
            script.contains("window.__TS_GAZE_MODE = \"smart\";"),
            "smart mode must set window.__TS_GAZE_MODE before the bundle runs"
        );
    }

    /// "off" (and any unrecognised mode) must never inject the gaze
    /// bundle — a stray gaze script running while the user picked "off"
    /// would mean spending CPU/battery on inference nobody asked for.
    #[test]
    fn gaze_never_injects_outside_smart_mode() {
        for mode in ["off", "blur", "", "bogus"] {
            let script = gaze_script(mode);
            assert!(
                script.is_empty(),
                "mode {mode:?} must not inject the gaze bundle, got {} bytes",
                script.len()
            );
        }
    }

    /// gaze_mode() must fall back to "off" for anything it doesn't
    /// recognise, never silently pass an unknown string through to the
    /// webview-building code.
    #[test]
    fn unknown_gaze_mode_falls_back_to_off() {
        assert_eq!(gaze_mode("smart"), "smart");
        assert_eq!(gaze_mode("blur"), "blur");
        assert_eq!(gaze_mode("off"), "off");
        assert_eq!(gaze_mode("nonsense"), "off");
        assert_eq!(gaze_mode(""), "off");
    }
}
